// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

package db

import (
	"context"
	"net/netip"
	"time"
)

const consumeEmailVerification = `-- name: ConsumeEmailVerification :one
DELETE FROM email_verification_tokens
WHERE token = $1
  AND expires_at > NOW()
RETURNING user_id
`

func (q *Queries) ConsumeEmailVerification(ctx context.Context, token string) (int, error) {
	row := q.db.QueryRow(ctx, consumeEmailVerification, token)
	var user_id int
	err := row.Scan(&user_id)
	return user_id, err
}

const consumePasswordResetToken = `-- name: ConsumePasswordResetToken :one
DELETE FROM password_reset_tokens
WHERE token = $1
  AND expires_at > NOW()
RETURNING user_id
`

func (q *Queries) ConsumePasswordResetToken(ctx context.Context, token string) (int, error) {
	row := q.db.QueryRow(ctx, consumePasswordResetToken, token)
	var user_id int
	err := row.Scan(&user_id)
	return user_id, err
}

const createEmailVerification = `-- name: CreateEmailVerification :exec
INSERT INTO email_verification_tokens (token, user_id, expires_at)
VALUES ($1, $2, $3)
`

type CreateEmailVerificationParams struct {
	Token     string
	UserID    int
	ExpiresAt time.Time
}

func (q *Queries) CreateEmailVerification(ctx context.Context, arg CreateEmailVerificationParams) error {
	_, err := q.db.Exec(ctx, createEmailVerification, arg.Token, arg.UserID, arg.ExpiresAt)
	return err
}

const createPasswordResetToken = `-- name: CreatePasswordResetToken :exec
INSERT INTO password_reset_tokens (token, user_id, expires_at)
VALUES ($1, $2, $3)
`

type CreatePasswordResetTokenParams struct {
	Token     string
	UserID    int
	ExpiresAt time.Time
}

func (q *Queries) CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) error {
	_, err := q.db.Exec(ctx, createPasswordResetToken, arg.Token, arg.UserID, arg.ExpiresAt)
	return err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (
    id, user_id, ip_address, user_agent, expires_at
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, user_id, ip_address, user_agent, expires_at, created_at
`

type CreateSessionParams struct {
	ID        string
	UserID    int
	IpAddress netip.Addr
	UserAgent string
	ExpiresAt time.Time
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.IpAddress,
		arg.UserAgent,
		arg.ExpiresAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.IpAddress,
		&i.UserAgent,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, pw_hash)
VALUES ($1, $2)
RETURNING id
`

type CreateUserParams struct {
	Email  string
	PwHash string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (int, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.PwHash)
	var id int
	err := row.Scan(&id)
	return id, err
}

const deleteEmailVerificationByUserID = `-- name: DeleteEmailVerificationByUserID :exec
DELETE FROM email_verification_tokens WHERE user_id = $1
`

func (q *Queries) DeleteEmailVerificationByUserID(ctx context.Context, userID int) error {
	_, err := q.db.Exec(ctx, deleteEmailVerificationByUserID, userID)
	return err
}

const deletePasswordResetTokensByUserID = `-- name: DeletePasswordResetTokensByUserID :exec
DELETE FROM password_reset_tokens WHERE user_id = $1
`

func (q *Queries) DeletePasswordResetTokensByUserID(ctx context.Context, userID int) error {
	_, err := q.db.Exec(ctx, deletePasswordResetTokensByUserID, userID)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE id = $1
`

func (q *Queries) DeleteSession(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteSession, id)
	return err
}

const deleteSessionsByUserID = `-- name: DeleteSessionsByUserID :exec
DELETE FROM sessions WHERE user_id = $1
`

func (q *Queries) DeleteSessionsByUserID(ctx context.Context, userID int) error {
	_, err := q.db.Exec(ctx, deleteSessionsByUserID, userID)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, pw_hash, is_active, is_verified, created_at, updated_at, last_login_at FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PwHash,
		&i.IsActive,
		&i.IsVerified,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const getUserBySessionID = `-- name: GetUserBySessionID :one
SELECT
    u.id,
    u.email,
    u.is_active,
    u.is_verified,
    s.id AS session_id,
    s.expires_at
FROM sessions s
JOIN users u ON s.user_id = u.id
WHERE s.id = $1
  AND s.expires_at > CURRENT_TIMESTAMP
`

type GetUserBySessionIDRow struct {
	ID         int
	Email      string
	IsActive   bool
	IsVerified bool
	SessionID  string
	ExpiresAt  time.Time
}

func (q *Queries) GetUserBySessionID(ctx context.Context, id string) (GetUserBySessionIDRow, error) {
	row := q.db.QueryRow(ctx, getUserBySessionID, id)
	var i GetUserBySessionIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.IsActive,
		&i.IsVerified,
		&i.SessionID,
		&i.ExpiresAt,
	)
	return i, err
}

const updateLastLogin = `-- name: UpdateLastLogin :exec
UPDATE users
SET last_login_at = NOW()
WHERE id = $1
`

func (q *Queries) UpdateLastLogin(ctx context.Context, id int) error {
	_, err := q.db.Exec(ctx, updateLastLogin, id)
	return err
}

const updatePassword = `-- name: UpdatePassword :exec
UPDATE users
SET pw_hash = $2, updated_at = NOW()
WHERE id = $1
`

type UpdatePasswordParams struct {
	ID     int
	PwHash string
}

func (q *Queries) UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error {
	_, err := q.db.Exec(ctx, updatePassword, arg.ID, arg.PwHash)
	return err
}

const verifyUser = `-- name: VerifyUser :exec
UPDATE users
SET is_verified = true
WHERE id = $1
`

func (q *Queries) VerifyUser(ctx context.Context, id int) error {
	_, err := q.db.Exec(ctx, verifyUser, id)
	return err
}
