// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: buildings.sql

package db

import (
	"context"
	"time"
)

const decrementAndListCompleted = `-- name: DecrementAndListCompleted :many
WITH decremented AS (
    UPDATE kingdom_constructions
    SET ticks_remaining = ticks_remaining - 1
    WHERE ticks_remaining > 0
    RETURNING id, kingdom_id, building_type, ticks_remaining, ticks_total, started_at
)
SELECT id, kingdom_id, building_type, ticks_remaining, ticks_total, started_at FROM decremented WHERE ticks_remaining = 0
`

type DecrementAndListCompletedRow struct {
	ID             int
	KingdomID      int
	BuildingType   string
	TicksRemaining int
	TicksTotal     int
	StartedAt      time.Time
}

func (q *Queries) DecrementAndListCompleted(ctx context.Context) ([]DecrementAndListCompletedRow, error) {
	rows, err := q.db.Query(ctx, decrementAndListCompleted)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DecrementAndListCompletedRow
	for rows.Next() {
		var i DecrementAndListCompletedRow
		if err := rows.Scan(
			&i.ID,
			&i.KingdomID,
			&i.BuildingType,
			&i.TicksRemaining,
			&i.TicksTotal,
			&i.StartedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deductBuildingCost = `-- name: DeductBuildingCost :one
UPDATE kingdoms SET
    wood      = wood      - $1,
    stone     = stone     - $2,
    food      = food      - $3,
    mana      = mana      - $4,
    devotion  = devotion  - $5,
    knowledge = knowledge - $6,
    updated_at = NOW()
WHERE id = $7
    AND wood      >= $1
    AND stone     >= $2
    AND food      >= $3
    AND mana      >= $4
    AND devotion  >= $5
    AND knowledge >= $6
RETURNING id
`

type DeductBuildingCostParams struct {
	WoodCost      int
	StoneCost     int
	FoodCost      int
	ManaCost      int
	DevotionCost  int
	KnowledgeCost int
	KingdomID     int
}

func (q *Queries) DeductBuildingCost(ctx context.Context, arg DeductBuildingCostParams) (int, error) {
	row := q.db.QueryRow(ctx, deductBuildingCost,
		arg.WoodCost,
		arg.StoneCost,
		arg.FoodCost,
		arg.ManaCost,
		arg.DevotionCost,
		arg.KnowledgeCost,
		arg.KingdomID,
	)
	var id int
	err := row.Scan(&id)
	return id, err
}

const deleteConstruction = `-- name: DeleteConstruction :exec
DELETE FROM kingdom_constructions
WHERE kingdom_id = $1
`

func (q *Queries) DeleteConstruction(ctx context.Context, kingdomID int) error {
	_, err := q.db.Exec(ctx, deleteConstruction, kingdomID)
	return err
}

const getAllKingdomBuildings = `-- name: GetAllKingdomBuildings :many
SELECT kingdom_id, building_type, count, created_at, updated_at FROM kingdom_buildings
ORDER BY kingdom_id
`

func (q *Queries) GetAllKingdomBuildings(ctx context.Context) ([]KingdomBuilding, error) {
	rows, err := q.db.Query(ctx, getAllKingdomBuildings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []KingdomBuilding
	for rows.Next() {
		var i KingdomBuilding
		if err := rows.Scan(
			&i.KingdomID,
			&i.BuildingType,
			&i.Count,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getKingdomBuildings = `-- name: GetKingdomBuildings :many
SELECT kingdom_id, building_type, count, created_at, updated_at FROM kingdom_buildings
WHERE kingdom_id = $1
`

func (q *Queries) GetKingdomBuildings(ctx context.Context, kingdomID int) ([]KingdomBuilding, error) {
	rows, err := q.db.Query(ctx, getKingdomBuildings, kingdomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []KingdomBuilding
	for rows.Next() {
		var i KingdomBuilding
		if err := rows.Scan(
			&i.KingdomID,
			&i.BuildingType,
			&i.Count,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getKingdomConstruction = `-- name: GetKingdomConstruction :one
SELECT id, kingdom_id, building_type, ticks_remaining, ticks_total, started_at FROM kingdom_constructions
WHERE kingdom_id = $1
`

func (q *Queries) GetKingdomConstruction(ctx context.Context, kingdomID int) (KingdomConstruction, error) {
	row := q.db.QueryRow(ctx, getKingdomConstruction, kingdomID)
	var i KingdomConstruction
	err := row.Scan(
		&i.ID,
		&i.KingdomID,
		&i.BuildingType,
		&i.TicksRemaining,
		&i.TicksTotal,
		&i.StartedAt,
	)
	return i, err
}

const incrementKingdomBuilding = `-- name: IncrementKingdomBuilding :exec
INSERT INTO kingdom_buildings (kingdom_id, building_type, count)
VALUES ($1, $2, 1)
ON CONFLICT (kingdom_id, building_type)
DO UPDATE SET
    count      = kingdom_buildings.count + 1,
    updated_at = NOW()
`

type IncrementKingdomBuildingParams struct {
	KingdomID    int
	BuildingType string
}

func (q *Queries) IncrementKingdomBuilding(ctx context.Context, arg IncrementKingdomBuildingParams) error {
	_, err := q.db.Exec(ctx, incrementKingdomBuilding, arg.KingdomID, arg.BuildingType)
	return err
}

const startConstruction = `-- name: StartConstruction :exec
INSERT INTO kingdom_constructions (kingdom_id, building_type, ticks_remaining, ticks_total)
VALUES ($1, $2, $3, $3)
`

type StartConstructionParams struct {
	KingdomID      int
	BuildingType   string
	TicksRemaining int
}

func (q *Queries) StartConstruction(ctx context.Context, arg StartConstructionParams) error {
	_, err := q.db.Exec(ctx, startConstruction, arg.KingdomID, arg.BuildingType, arg.TicksRemaining)
	return err
}
