// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: campaigns.sql

package db

import (
	"context"
	"time"
)

const advanceCampaignStatus = `-- name: AdvanceCampaignStatus :exec
UPDATE kingdom_campaigns
SET status = $2, ticks_remaining = $3
WHERE id = $1
`

type AdvanceCampaignStatusParams struct {
	ID             int
	Status         string
	TicksRemaining int
}

func (q *Queries) AdvanceCampaignStatus(ctx context.Context, arg AdvanceCampaignStatusParams) error {
	_, err := q.db.Exec(ctx, advanceCampaignStatus, arg.ID, arg.Status, arg.TicksRemaining)
	return err
}

const bulkActivateCampaigns = `-- name: BulkActivateCampaigns :exec
UPDATE kingdom_campaigns
SET status = 'active', ticks_remaining = action_ticks
WHERE id = ANY($1::bigint[])
`

func (q *Queries) BulkActivateCampaigns(ctx context.Context, ids []int) error {
	_, err := q.db.Exec(ctx, bulkActivateCampaigns, ids)
	return err
}

const bulkDeleteCampaigns = `-- name: BulkDeleteCampaigns :exec
DELETE FROM kingdom_campaigns
WHERE id = ANY($1::bigint[])
`

func (q *Queries) BulkDeleteCampaigns(ctx context.Context, ids []int) error {
	_, err := q.db.Exec(ctx, bulkDeleteCampaigns, ids)
	return err
}

const bulkReturnCampaigns = `-- name: BulkReturnCampaigns :exec
UPDATE kingdom_campaigns
SET status = 'returning', ticks_remaining = travel_ticks
WHERE id = ANY($1::bigint[])
`

func (q *Queries) BulkReturnCampaigns(ctx context.Context, ids []int) error {
	_, err := q.db.Exec(ctx, bulkReturnCampaigns, ids)
	return err
}

const bulkUpdateCampaignCounts = `-- name: BulkUpdateCampaignCounts :exec
UPDATE kingdom_campaigns
SET count = data.count
FROM (
    SELECT unnest($1::bigint[]) AS id,
           unnest($2::int[]) AS count
) AS data
WHERE kingdom_campaigns.id = data.id
`

type BulkUpdateCampaignCountsParams struct {
	Ids    []int
	Counts []int
}

func (q *Queries) BulkUpdateCampaignCounts(ctx context.Context, arg BulkUpdateCampaignCountsParams) error {
	_, err := q.db.Exec(ctx, bulkUpdateCampaignCounts, arg.Ids, arg.Counts)
	return err
}

const cancelCampaign = `-- name: CancelCampaign :one
UPDATE kingdom_campaigns
SET status = 'returning', ticks_remaining = travel_ticks
WHERE id = $1
  AND kingdom_id = $2
  AND status != 'returning'
RETURNING id
`

type CancelCampaignParams struct {
	ID        int
	KingdomID int
}

// Atomically verifies ownership and non-returning status, then sets the campaign
// to returning. Returns no rows if the campaign does not exist, belongs to a
// different kingdom, or is already returning — all treated as a no-op by the caller.
func (q *Queries) CancelCampaign(ctx context.Context, arg CancelCampaignParams) (int, error) {
	row := q.db.QueryRow(ctx, cancelCampaign, arg.ID, arg.KingdomID)
	var id int
	err := row.Scan(&id)
	return id, err
}

const createCampaignIfAvailable = `-- name: CreateCampaignIfAvailable :one
WITH available AS (
    SELECT count FROM kingdom_available_units
    WHERE kingdom_id = $1 AND unit_type = $3
)
INSERT INTO kingdom_campaigns (
    kingdom_id, target_kingdom_id, unit_type, count,
    action, ticks_remaining, action_ticks, travel_ticks
)
SELECT $1, $2, $3, $4,
       $5, $6, $7, $8
FROM available
WHERE available.count >= $4
RETURNING id, kingdom_id, target_kingdom_id, unit_type, count, action, status, ticks_remaining, action_ticks, travel_ticks, created_at
`

type CreateCampaignIfAvailableParams struct {
	KingdomID       int
	TargetKingdomID int
	UnitType        string
	SendCount       int
	Action          string
	TicksRemaining  int
	ActionTicks     int
	TravelTicks     int
}

// Atomically checks that enough units are available (via kingdom_available_units
// view) and inserts the campaign in one statement. Returns no rows if the
// available count is insufficient, which the caller maps to "not enough units".
func (q *Queries) CreateCampaignIfAvailable(ctx context.Context, arg CreateCampaignIfAvailableParams) (KingdomCampaign, error) {
	row := q.db.QueryRow(ctx, createCampaignIfAvailable,
		arg.KingdomID,
		arg.TargetKingdomID,
		arg.UnitType,
		arg.SendCount,
		arg.Action,
		arg.TicksRemaining,
		arg.ActionTicks,
		arg.TravelTicks,
	)
	var i KingdomCampaign
	err := row.Scan(
		&i.ID,
		&i.KingdomID,
		&i.TargetKingdomID,
		&i.UnitType,
		&i.Count,
		&i.Action,
		&i.Status,
		&i.TicksRemaining,
		&i.ActionTicks,
		&i.TravelTicks,
		&i.CreatedAt,
	)
	return i, err
}

const decrementAndListCampaignsAtZero = `-- name: DecrementAndListCampaignsAtZero :many
WITH decremented AS (
    UPDATE kingdom_campaigns
    SET ticks_remaining = ticks_remaining - 1
    WHERE ticks_remaining > 0
    RETURNING id, kingdom_id, target_kingdom_id, unit_type, count, action, status, ticks_remaining, action_ticks, travel_ticks, created_at
)
SELECT id, kingdom_id, target_kingdom_id, unit_type, count, action, status, ticks_remaining, action_ticks, travel_ticks, created_at FROM decremented WHERE ticks_remaining = 0
`

type DecrementAndListCampaignsAtZeroRow struct {
	ID              int
	KingdomID       int
	TargetKingdomID int
	UnitType        string
	Count           int
	Action          string
	Status          string
	TicksRemaining  int
	ActionTicks     int
	TravelTicks     int
	CreatedAt       time.Time
}

func (q *Queries) DecrementAndListCampaignsAtZero(ctx context.Context) ([]DecrementAndListCampaignsAtZeroRow, error) {
	rows, err := q.db.Query(ctx, decrementAndListCampaignsAtZero)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DecrementAndListCampaignsAtZeroRow
	for rows.Next() {
		var i DecrementAndListCampaignsAtZeroRow
		if err := rows.Scan(
			&i.ID,
			&i.KingdomID,
			&i.TargetKingdomID,
			&i.UnitType,
			&i.Count,
			&i.Action,
			&i.Status,
			&i.TicksRemaining,
			&i.ActionTicks,
			&i.TravelTicks,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteCampaign = `-- name: DeleteCampaign :exec
DELETE FROM kingdom_campaigns
WHERE id = $1
`

func (q *Queries) DeleteCampaign(ctx context.Context, id int) error {
	_, err := q.db.Exec(ctx, deleteCampaign, id)
	return err
}

const getActiveCampaignsReadyForCombat = `-- name: GetActiveCampaignsReadyForCombat :many
SELECT id, kingdom_id, target_kingdom_id, unit_type, count, action, status, ticks_remaining, action_ticks, travel_ticks, created_at FROM kingdom_campaigns
WHERE status = 'active'
  AND ticks_remaining > 0
`

func (q *Queries) GetActiveCampaignsReadyForCombat(ctx context.Context) ([]KingdomCampaign, error) {
	rows, err := q.db.Query(ctx, getActiveCampaignsReadyForCombat)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []KingdomCampaign
	for rows.Next() {
		var i KingdomCampaign
		if err := rows.Scan(
			&i.ID,
			&i.KingdomID,
			&i.TargetKingdomID,
			&i.UnitType,
			&i.Count,
			&i.Action,
			&i.Status,
			&i.TicksRemaining,
			&i.ActionTicks,
			&i.TravelTicks,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCampaignsForKingdom = `-- name: GetCampaignsForKingdom :many
SELECT id, kingdom_id, target_kingdom_id, unit_type, count, action, status, ticks_remaining, action_ticks, travel_ticks, created_at FROM kingdom_campaigns
WHERE kingdom_id = $1
ORDER BY created_at ASC
`

func (q *Queries) GetCampaignsForKingdom(ctx context.Context, kingdomID int) ([]KingdomCampaign, error) {
	rows, err := q.db.Query(ctx, getCampaignsForKingdom, kingdomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []KingdomCampaign
	for rows.Next() {
		var i KingdomCampaign
		if err := rows.Scan(
			&i.ID,
			&i.KingdomID,
			&i.TargetKingdomID,
			&i.UnitType,
			&i.Count,
			&i.Action,
			&i.Status,
			&i.TicksRemaining,
			&i.ActionTicks,
			&i.TravelTicks,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
