// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: campaigns.sql

package db

import (
	"context"
	"time"
)

const bulkActivateCampaigns = `-- name: BulkActivateCampaigns :exec
UPDATE kingdom_campaigns
SET status = 'active', ticks_remaining = action_ticks
WHERE id = ANY($1::bigint[])
`

func (q *Queries) BulkActivateCampaigns(ctx context.Context, ids []int) error {
	_, err := q.db.Exec(ctx, bulkActivateCampaigns, ids)
	return err
}

const bulkDeleteCampaignUnitsZero = `-- name: BulkDeleteCampaignUnitsZero :exec
DELETE FROM kingdom_campaign_units
WHERE (campaign_id, unit_type) IN (
    SELECT unnest($1::bigint[]), unnest($2::text[])
)
`

type BulkDeleteCampaignUnitsZeroParams struct {
	CampaignIds []int
	UnitTypes   []string
}

func (q *Queries) BulkDeleteCampaignUnitsZero(ctx context.Context, arg BulkDeleteCampaignUnitsZeroParams) error {
	_, err := q.db.Exec(ctx, bulkDeleteCampaignUnitsZero, arg.CampaignIds, arg.UnitTypes)
	return err
}

const bulkDeleteCampaigns = `-- name: BulkDeleteCampaigns :exec
DELETE FROM kingdom_campaigns
WHERE id = ANY($1::bigint[])
`

func (q *Queries) BulkDeleteCampaigns(ctx context.Context, ids []int) error {
	_, err := q.db.Exec(ctx, bulkDeleteCampaigns, ids)
	return err
}

const bulkRestoreLegionUnits = `-- name: BulkRestoreLegionUnits :exec
INSERT INTO kingdom_legion_units (legion_id, unit_type, count)
SELECT kc.legion_id, kcu.unit_type, kcu.count
FROM kingdom_campaign_units kcu
JOIN kingdom_campaigns kc ON kc.id = kcu.campaign_id
WHERE kc.id = ANY($1::bigint[])
ON CONFLICT (legion_id, unit_type)
DO UPDATE SET count = kingdom_legion_units.count + EXCLUDED.count
`

func (q *Queries) BulkRestoreLegionUnits(ctx context.Context, ids []int) error {
	_, err := q.db.Exec(ctx, bulkRestoreLegionUnits, ids)
	return err
}

const bulkReturnCampaigns = `-- name: BulkReturnCampaigns :exec
UPDATE kingdom_campaigns
SET status = 'returning', ticks_remaining = travel_ticks
WHERE id = ANY($1::bigint[])
`

func (q *Queries) BulkReturnCampaigns(ctx context.Context, ids []int) error {
	_, err := q.db.Exec(ctx, bulkReturnCampaigns, ids)
	return err
}

const bulkUpdateCampaignUnitCounts = `-- name: BulkUpdateCampaignUnitCounts :exec
UPDATE kingdom_campaign_units
SET count = data.count
FROM (
    SELECT
        unnest($1::bigint[]) AS campaign_id,
        unnest($2::text[])     AS unit_type,
        unnest($3::int[])          AS count
) AS data
WHERE kingdom_campaign_units.campaign_id = data.campaign_id
  AND kingdom_campaign_units.unit_type   = data.unit_type
`

type BulkUpdateCampaignUnitCountsParams struct {
	CampaignIds []int
	UnitTypes   []string
	Counts      []int
}

func (q *Queries) BulkUpdateCampaignUnitCounts(ctx context.Context, arg BulkUpdateCampaignUnitCountsParams) error {
	_, err := q.db.Exec(ctx, bulkUpdateCampaignUnitCounts, arg.CampaignIds, arg.UnitTypes, arg.Counts)
	return err
}

const cancelCampaign = `-- name: CancelCampaign :one
UPDATE kingdom_campaigns
SET status = 'returning',
    ticks_remaining = CASE
        WHEN status = 'en_route' THEN GREATEST(travel_ticks - ticks_remaining, 1)
        ELSE travel_ticks
    END
WHERE id = $1
  AND kingdom_id = $2
  AND status != 'returning'
RETURNING id
`

type CancelCampaignParams struct {
	ID        int
	KingdomID int
}

// Atomically verifies ownership and non-returning status, then sets the campaign
// to returning. Returns no rows if the campaign does not exist, belongs to a
// different kingdom, or is already returning — all treated as a no-op by the caller.
// When en_route, the return trip is proportional to distance already traveled;
// when active (at target), the full travel_ticks applies.
func (q *Queries) CancelCampaign(ctx context.Context, arg CancelCampaignParams) (int, error) {
	row := q.db.QueryRow(ctx, cancelCampaign, arg.ID, arg.KingdomID)
	var id int
	err := row.Scan(&id)
	return id, err
}

const createCampaign = `-- name: CreateCampaign :one
INSERT INTO kingdom_campaigns (
    kingdom_id, target_kingdom_id, legion_id,
    action, ticks_remaining, action_ticks, travel_ticks
)
VALUES (
    $1, $2, $3,
    $4, $5, $6, $7
)
RETURNING id, kingdom_id, target_kingdom_id, legion_id, action, status, ticks_remaining, action_ticks, travel_ticks, created_at
`

type CreateCampaignParams struct {
	KingdomID       int
	TargetKingdomID int
	LegionID        int
	Action          string
	TicksRemaining  int
	ActionTicks     int
	TravelTicks     int
}

func (q *Queries) CreateCampaign(ctx context.Context, arg CreateCampaignParams) (KingdomCampaign, error) {
	row := q.db.QueryRow(ctx, createCampaign,
		arg.KingdomID,
		arg.TargetKingdomID,
		arg.LegionID,
		arg.Action,
		arg.TicksRemaining,
		arg.ActionTicks,
		arg.TravelTicks,
	)
	var i KingdomCampaign
	err := row.Scan(
		&i.ID,
		&i.KingdomID,
		&i.TargetKingdomID,
		&i.LegionID,
		&i.Action,
		&i.Status,
		&i.TicksRemaining,
		&i.ActionTicks,
		&i.TravelTicks,
		&i.CreatedAt,
	)
	return i, err
}

const decrementAndListCampaignsAtZero = `-- name: DecrementAndListCampaignsAtZero :many
WITH decremented AS (
    UPDATE kingdom_campaigns
    SET ticks_remaining = ticks_remaining - 1
    WHERE ticks_remaining > 0
    RETURNING id, kingdom_id, target_kingdom_id, legion_id, action, status, ticks_remaining, action_ticks, travel_ticks, created_at
)
SELECT id, kingdom_id, target_kingdom_id, legion_id, action, status, ticks_remaining, action_ticks, travel_ticks, created_at FROM decremented WHERE ticks_remaining = 0
`

type DecrementAndListCampaignsAtZeroRow struct {
	ID              int
	KingdomID       int
	TargetKingdomID int
	LegionID        int
	Action          string
	Status          string
	TicksRemaining  int
	ActionTicks     int
	TravelTicks     int
	CreatedAt       time.Time
}

func (q *Queries) DecrementAndListCampaignsAtZero(ctx context.Context) ([]DecrementAndListCampaignsAtZeroRow, error) {
	rows, err := q.db.Query(ctx, decrementAndListCampaignsAtZero)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DecrementAndListCampaignsAtZeroRow
	for rows.Next() {
		var i DecrementAndListCampaignsAtZeroRow
		if err := rows.Scan(
			&i.ID,
			&i.KingdomID,
			&i.TargetKingdomID,
			&i.LegionID,
			&i.Action,
			&i.Status,
			&i.TicksRemaining,
			&i.ActionTicks,
			&i.TravelTicks,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getActiveCampaignsReadyForCombat = `-- name: GetActiveCampaignsReadyForCombat :many
SELECT id, kingdom_id, target_kingdom_id, legion_id, action, status, ticks_remaining, action_ticks, travel_ticks, created_at FROM kingdom_campaigns
WHERE status = 'active'
  AND ticks_remaining > 0
`

func (q *Queries) GetActiveCampaignsReadyForCombat(ctx context.Context) ([]KingdomCampaign, error) {
	rows, err := q.db.Query(ctx, getActiveCampaignsReadyForCombat)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []KingdomCampaign
	for rows.Next() {
		var i KingdomCampaign
		if err := rows.Scan(
			&i.ID,
			&i.KingdomID,
			&i.TargetKingdomID,
			&i.LegionID,
			&i.Action,
			&i.Status,
			&i.TicksRemaining,
			&i.ActionTicks,
			&i.TravelTicks,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCampaignUnitsByCampaignIDs = `-- name: GetCampaignUnitsByCampaignIDs :many
SELECT campaign_id, unit_type, count FROM kingdom_campaign_units
WHERE campaign_id = ANY($1::bigint[])
`

func (q *Queries) GetCampaignUnitsByCampaignIDs(ctx context.Context, ids []int) ([]KingdomCampaignUnit, error) {
	rows, err := q.db.Query(ctx, getCampaignUnitsByCampaignIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []KingdomCampaignUnit
	for rows.Next() {
		var i KingdomCampaignUnit
		if err := rows.Scan(&i.CampaignID, &i.UnitType, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCampaignsForKingdom = `-- name: GetCampaignsForKingdom :many
SELECT
    kc.id,
    kc.kingdom_id,
    kc.target_kingdom_id,
    kc.legion_id,
    kl.name    AS legion_name,
    kl.number  AS legion_number,
    kc.action,
    kc.status,
    kc.ticks_remaining,
    kc.action_ticks,
    kc.travel_ticks,
    kc.created_at
FROM kingdom_campaigns kc
JOIN kingdom_legions kl ON kl.id = kc.legion_id
WHERE kc.kingdom_id = $1
ORDER BY kc.created_at ASC
`

type GetCampaignsForKingdomRow struct {
	ID              int
	KingdomID       int
	TargetKingdomID int
	LegionID        int
	LegionName      string
	LegionNumber    int
	Action          string
	Status          string
	TicksRemaining  int
	ActionTicks     int
	TravelTicks     int
	CreatedAt       time.Time
}

func (q *Queries) GetCampaignsForKingdom(ctx context.Context, kingdomID int) ([]GetCampaignsForKingdomRow, error) {
	rows, err := q.db.Query(ctx, getCampaignsForKingdom, kingdomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCampaignsForKingdomRow
	for rows.Next() {
		var i GetCampaignsForKingdomRow
		if err := rows.Scan(
			&i.ID,
			&i.KingdomID,
			&i.TargetKingdomID,
			&i.LegionID,
			&i.LegionName,
			&i.LegionNumber,
			&i.Action,
			&i.Status,
			&i.TicksRemaining,
			&i.ActionTicks,
			&i.TravelTicks,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isLegionDeployed = `-- name: IsLegionDeployed :one
SELECT EXISTS(
    SELECT 1 FROM kingdom_campaigns WHERE legion_id = $1
) AS deployed
`

func (q *Queries) IsLegionDeployed(ctx context.Context, legionID int) (bool, error) {
	row := q.db.QueryRow(ctx, isLegionDeployed, legionID)
	var deployed bool
	err := row.Scan(&deployed)
	return deployed, err
}

const listCampaignUnitsForKingdom = `-- name: ListCampaignUnitsForKingdom :many
SELECT kcu.campaign_id, kcu.unit_type, kcu.count
FROM kingdom_campaign_units kcu
JOIN kingdom_campaigns kc ON kc.id = kcu.campaign_id
WHERE kc.kingdom_id = $1
`

func (q *Queries) ListCampaignUnitsForKingdom(ctx context.Context, kingdomID int) ([]KingdomCampaignUnit, error) {
	rows, err := q.db.Query(ctx, listCampaignUnitsForKingdom, kingdomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []KingdomCampaignUnit
	for rows.Next() {
		var i KingdomCampaignUnit
		if err := rows.Scan(&i.CampaignID, &i.UnitType, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const snapshotLegionUnitsIntoCampaign = `-- name: SnapshotLegionUnitsIntoCampaign :exec
INSERT INTO kingdom_campaign_units (campaign_id, unit_type, count)
SELECT $1, unit_type, count
FROM kingdom_legion_units
WHERE legion_id = $2
`

type SnapshotLegionUnitsIntoCampaignParams struct {
	CampaignID int
	LegionID   int
}

func (q *Queries) SnapshotLegionUnitsIntoCampaign(ctx context.Context, arg SnapshotLegionUnitsIntoCampaignParams) error {
	_, err := q.db.Exec(ctx, snapshotLegionUnitsIntoCampaign, arg.CampaignID, arg.LegionID)
	return err
}
