// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: combat_log.sql

package db

import (
	"context"
	"time"
)

const bulkInsertCombatLogParticipants = `-- name: BulkInsertCombatLogParticipants :exec
INSERT INTO kingdom_combat_log_participants (combat_log_id, kingdom_id, role, population_gained)
SELECT $1, data.kingdom_id, data.role, data.population_gained
FROM (
    SELECT
        unnest($2::bigint[]) AS kingdom_id,
        unnest($3::text[])         AS role,
        unnest($4::int[]) AS population_gained
) AS data
`

type BulkInsertCombatLogParticipantsParams struct {
	CombatLogID      int
	KingdomIds       []int
	Roles            []string
	PopulationGained []int
}

func (q *Queries) BulkInsertCombatLogParticipants(ctx context.Context, arg BulkInsertCombatLogParticipantsParams) error {
	_, err := q.db.Exec(ctx, bulkInsertCombatLogParticipants,
		arg.CombatLogID,
		arg.KingdomIds,
		arg.Roles,
		arg.PopulationGained,
	)
	return err
}

const getRecentCombatLogs = `-- name: GetRecentCombatLogs :many
WITH my_log_ids AS (
    SELECT l.id, l.occurred_at
    FROM kingdom_combat_log l
    JOIN kingdom_combat_log_participants p ON l.id = p.combat_log_id
    WHERE p.kingdom_id = $1
    ORDER BY l.occurred_at DESC
    LIMIT 5
)
SELECT l.id, l.tick_id, l.target_kingdom_id, l.attacker_units, l.defender_units,
       l.attacker_power, l.defender_power, l.winner,
       l.attacker_casualties, l.defender_casualties, l.population_stolen, l.occurred_at,
       p.kingdom_id AS participant_kingdom_id,
       k.name       AS participant_name,
       p.role       AS participant_role,
       p.population_gained
FROM kingdom_combat_log l
JOIN my_log_ids ml ON l.id = ml.id
JOIN kingdom_combat_log_participants p ON l.id = p.combat_log_id
JOIN kingdoms k ON p.kingdom_id = k.id
ORDER BY l.occurred_at DESC, l.id, p.role, k.name
`

type GetRecentCombatLogsRow struct {
	ID                   int
	TickID               int
	TargetKingdomID      int
	AttackerUnits        []byte
	DefenderUnits        []byte
	AttackerPower        int
	DefenderPower        int
	Winner               string
	AttackerCasualties   int
	DefenderCasualties   int
	PopulationStolen     int
	OccurredAt           time.Time
	ParticipantKingdomID int
	ParticipantName      string
	ParticipantRole      string
	PopulationGained     int
}

func (q *Queries) GetRecentCombatLogs(ctx context.Context, kingdomID int) ([]GetRecentCombatLogsRow, error) {
	rows, err := q.db.Query(ctx, getRecentCombatLogs, kingdomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRecentCombatLogsRow
	for rows.Next() {
		var i GetRecentCombatLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.TickID,
			&i.TargetKingdomID,
			&i.AttackerUnits,
			&i.DefenderUnits,
			&i.AttackerPower,
			&i.DefenderPower,
			&i.Winner,
			&i.AttackerCasualties,
			&i.DefenderCasualties,
			&i.PopulationStolen,
			&i.OccurredAt,
			&i.ParticipantKingdomID,
			&i.ParticipantName,
			&i.ParticipantRole,
			&i.PopulationGained,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertCombatLog = `-- name: InsertCombatLog :one
INSERT INTO kingdom_combat_log (
    tick_id,
    target_kingdom_id,
    attacker_units, defender_units,
    attacker_power, defender_power,
    winner,
    attacker_casualties, defender_casualties,
    population_stolen
) VALUES (
    $1, $2,
    $3, $4,
    $5, $6,
    $7,
    $8, $9,
    $10
)
RETURNING id
`

type InsertCombatLogParams struct {
	TickID             int
	TargetKingdomID    int
	AttackerUnits      []byte
	DefenderUnits      []byte
	AttackerPower      int
	DefenderPower      int
	Winner             string
	AttackerCasualties int
	DefenderCasualties int
	PopulationStolen   int
}

func (q *Queries) InsertCombatLog(ctx context.Context, arg InsertCombatLogParams) (int, error) {
	row := q.db.QueryRow(ctx, insertCombatLog,
		arg.TickID,
		arg.TargetKingdomID,
		arg.AttackerUnits,
		arg.DefenderUnits,
		arg.AttackerPower,
		arg.DefenderPower,
		arg.Winner,
		arg.AttackerCasualties,
		arg.DefenderCasualties,
		arg.PopulationStolen,
	)
	var id int
	err := row.Scan(&id)
	return id, err
}
