// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: guilds.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const acceptGuildInvitation = `-- name: AcceptGuildInvitation :one
WITH member_count AS (
    SELECT COUNT(*) AS cnt
    FROM guild_memberships gm
    WHERE gm.guild_id = $1 AND gm.role IN ('member', 'officer', 'leader')
),
new_member AS (
    UPDATE guild_memberships AS gm_inv
    SET role = 'member', joined_at = NOW()
    WHERE gm_inv.id = $2
      AND gm_inv.kingdom_id = $3
      AND gm_inv.guild_id = $1
      AND gm_inv.role = 'invited'
      AND (SELECT cnt FROM member_count) < 20
    RETURNING gm_inv.kingdom_id
),
cancel_requests AS (
    DELETE FROM guild_memberships gm2
    WHERE gm2.kingdom_id = (SELECT kingdom_id FROM new_member)
      AND gm2.role = 'pending_approval'
),
cancel_invitations AS (
    DELETE FROM guild_memberships gm3
    WHERE gm3.kingdom_id = (SELECT kingdom_id FROM new_member)
      AND gm3.role = 'invited'
      AND gm3.guild_id != $1
)
SELECT kingdom_id FROM new_member
`

type AcceptGuildInvitationParams struct {
	GuildID      int
	InvitationID int
	KingdomID    int
}

// Atomically promotes the invited row to member if the guild is not full (< 20),
// cancels any pending join requests for the kingdom in other guilds, and
// cancels any other outstanding invitations. Returns no rows if the invitation
// is not found or the guild is at capacity.
func (q *Queries) AcceptGuildInvitation(ctx context.Context, arg AcceptGuildInvitationParams) (int, error) {
	row := q.db.QueryRow(ctx, acceptGuildInvitation, arg.GuildID, arg.InvitationID, arg.KingdomID)
	var kingdom_id int
	err := row.Scan(&kingdom_id)
	return kingdom_id, err
}

const activateGuild = `-- name: ActivateGuild :exec
WITH activate AS (
    UPDATE guilds
    SET status = 'active',
        founding_kingdom_ids = (
            SELECT array_agg(gm2.kingdom_id)
            FROM guild_memberships gm2
            WHERE gm2.guild_id = $1
              AND gm2.role IN ('applicant', 'supporter')
        ),
        updated_at = NOW()
    WHERE guilds.id = $1
)
UPDATE guild_memberships
SET role = CASE WHEN guild_memberships.role = 'applicant' THEN 'leader' ELSE 'member' END,
    joined_at = NOW()
WHERE guild_memberships.guild_id = $1
  AND guild_memberships.role IN ('applicant', 'supporter')
`

func (q *Queries) ActivateGuild(ctx context.Context, guildID int) error {
	_, err := q.db.Exec(ctx, activateGuild, guildID)
	return err
}

const approveMembershipIfNotFull = `-- name: ApproveMembershipIfNotFull :one
WITH member_count AS (
    SELECT COUNT(*) AS cnt
    FROM guild_memberships
    WHERE guild_memberships.guild_id = $1 AND guild_memberships.role IN ('member', 'officer', 'leader')
),
approved AS (
    UPDATE guild_memberships
    SET role = 'member', joined_at = NOW()
    WHERE guild_memberships.id = $2
      AND guild_memberships.guild_id = $1
      AND guild_memberships.role = 'pending_approval'
      AND (SELECT cnt FROM member_count) < 20
    RETURNING guild_memberships.kingdom_id
),
cleanup AS (
    DELETE FROM guild_memberships gm2
    WHERE gm2.kingdom_id = (SELECT kingdom_id FROM approved)
      AND gm2.role = 'pending_approval'
      AND gm2.guild_id != $1
),
cancel_invitations AS (
    DELETE FROM guild_memberships gm3
    WHERE gm3.kingdom_id = (SELECT kingdom_id FROM approved)
      AND gm3.role = 'invited'
)
SELECT kingdom_id FROM approved
`

type ApproveMembershipIfNotFullParams struct {
	GuildID      int
	MembershipID int
}

// Atomically checks the active member count and approves the pending request
// in one statement. Returns no rows if the guild is full (>= 20 active members)
// or the request no longer exists, which the caller maps to the appropriate error.
func (q *Queries) ApproveMembershipIfNotFull(ctx context.Context, arg ApproveMembershipIfNotFullParams) (int, error) {
	row := q.db.QueryRow(ctx, approveMembershipIfNotFull, arg.GuildID, arg.MembershipID)
	var kingdom_id int
	err := row.Scan(&kingdom_id)
	return kingdom_id, err
}

const cancelJoinRequest = `-- name: CancelJoinRequest :exec
DELETE FROM guild_memberships
WHERE kingdom_id = $1 AND guild_id = $2 AND role = 'pending_approval'
`

type CancelJoinRequestParams struct {
	KingdomID int
	GuildID   int
}

func (q *Queries) CancelJoinRequest(ctx context.Context, arg CancelJoinRequestParams) error {
	_, err := q.db.Exec(ctx, cancelJoinRequest, arg.KingdomID, arg.GuildID)
	return err
}

const cancelOtherPendingRequests = `-- name: CancelOtherPendingRequests :exec
DELETE FROM guild_memberships
WHERE kingdom_id = $1 AND guild_id != $2 AND role = 'pending_approval'
`

type CancelOtherPendingRequestsParams struct {
	KingdomID int
	GuildID   int
}

func (q *Queries) CancelOtherPendingRequests(ctx context.Context, arg CancelOtherPendingRequestsParams) error {
	_, err := q.db.Exec(ctx, cancelOtherPendingRequests, arg.KingdomID, arg.GuildID)
	return err
}

const cancelProposal = `-- name: CancelProposal :exec
DELETE FROM guilds WHERE id = $1 AND status = 'pending'
`

func (q *Queries) CancelProposal(ctx context.Context, id int) error {
	_, err := q.db.Exec(ctx, cancelProposal, id)
	return err
}

const countGuildSupporters = `-- name: CountGuildSupporters :one
SELECT COUNT(*) FROM guild_memberships
WHERE guild_id = $1 AND role IN ('applicant', 'supporter')
`

func (q *Queries) CountGuildSupporters(ctx context.Context, guildID int) (int, error) {
	row := q.db.QueryRow(ctx, countGuildSupporters, guildID)
	var count int
	err := row.Scan(&count)
	return count, err
}

const createGuild = `-- name: CreateGuild :one
WITH new_guild AS (
    INSERT INTO guilds (name, slug, description)
    VALUES ($1, $2, $3)
    RETURNING id, name, slug, description, status, founding_kingdom_ids, created_at, updated_at, settings
), insert_membership AS (
    INSERT INTO guild_memberships (guild_id, kingdom_id, role)
    SELECT id, $4::bigint, 'applicant'
    FROM new_guild
)
SELECT id, name, slug, description, status, founding_kingdom_ids, created_at, updated_at, settings FROM new_guild
`

type CreateGuildParams struct {
	Name             string
	Slug             string
	Description      string
	FounderKingdomID int
}

type CreateGuildRow struct {
	ID                 int
	Name               string
	Slug               string
	Description        string
	Status             string
	FoundingKingdomIds []int
	CreatedAt          time.Time
	UpdatedAt          time.Time
	Settings           []byte
}

func (q *Queries) CreateGuild(ctx context.Context, arg CreateGuildParams) (CreateGuildRow, error) {
	row := q.db.QueryRow(ctx, createGuild,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.FounderKingdomID,
	)
	var i CreateGuildRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Status,
		&i.FoundingKingdomIds,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Settings,
	)
	return i, err
}

const createGuildInvitation = `-- name: CreateGuildInvitation :exec
INSERT INTO guild_memberships (guild_id, kingdom_id, role)
VALUES ($1, $2, 'invited')
`

type CreateGuildInvitationParams struct {
	GuildID   int
	KingdomID int
}

func (q *Queries) CreateGuildInvitation(ctx context.Context, arg CreateGuildInvitationParams) error {
	_, err := q.db.Exec(ctx, createGuildInvitation, arg.GuildID, arg.KingdomID)
	return err
}

const createGuildMembership = `-- name: CreateGuildMembership :exec
INSERT INTO guild_memberships (guild_id, kingdom_id, role)
VALUES ($1, $2, $3)
`

type CreateGuildMembershipParams struct {
	GuildID   int
	KingdomID int
	Role      string
}

func (q *Queries) CreateGuildMembership(ctx context.Context, arg CreateGuildMembershipParams) error {
	_, err := q.db.Exec(ctx, createGuildMembership, arg.GuildID, arg.KingdomID, arg.Role)
	return err
}

const declineGuildInvitation = `-- name: DeclineGuildInvitation :one
DELETE FROM guild_memberships WHERE id = $1 AND kingdom_id = $2 AND role = 'invited' RETURNING guild_id
`

type DeclineGuildInvitationParams struct {
	ID        int
	KingdomID int
}

func (q *Queries) DeclineGuildInvitation(ctx context.Context, arg DeclineGuildInvitationParams) (int, error) {
	row := q.db.QueryRow(ctx, declineGuildInvitation, arg.ID, arg.KingdomID)
	var guild_id int
	err := row.Scan(&guild_id)
	return guild_id, err
}

const disbandGuild = `-- name: DisbandGuild :exec
DELETE FROM guilds WHERE id = $1
`

func (q *Queries) DisbandGuild(ctx context.Context, id int) error {
	_, err := q.db.Exec(ctx, disbandGuild, id)
	return err
}

const expirePendingGuilds = `-- name: ExpirePendingGuilds :exec
DELETE FROM guilds
WHERE status = 'pending' AND created_at < NOW() - INTERVAL '7 days'
`

func (q *Queries) ExpirePendingGuilds(ctx context.Context) error {
	_, err := q.db.Exec(ctx, expirePendingGuilds)
	return err
}

const getGuildByID = `-- name: GetGuildByID :one
SELECT id, name, slug, description, status, founding_kingdom_ids, created_at, updated_at, settings FROM guilds WHERE id = $1 LIMIT 1
`

func (q *Queries) GetGuildByID(ctx context.Context, id int) (Guild, error) {
	row := q.db.QueryRow(ctx, getGuildByID, id)
	var i Guild
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Status,
		&i.FoundingKingdomIds,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Settings,
	)
	return i, err
}

const getGuildBySlug = `-- name: GetGuildBySlug :one
SELECT id, name, slug, description, status, founding_kingdom_ids, created_at, updated_at, settings FROM guilds WHERE slug = $1 LIMIT 1
`

func (q *Queries) GetGuildBySlug(ctx context.Context, slug string) (Guild, error) {
	row := q.db.QueryRow(ctx, getGuildBySlug, slug)
	var i Guild
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.Status,
		&i.FoundingKingdomIds,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Settings,
	)
	return i, err
}

const getKingdomGuildInvitation = `-- name: GetKingdomGuildInvitation :one
SELECT id FROM guild_memberships WHERE kingdom_id = $1 AND guild_id = $2 AND role = 'invited' LIMIT 1
`

type GetKingdomGuildInvitationParams struct {
	KingdomID int
	GuildID   int
}

func (q *Queries) GetKingdomGuildInvitation(ctx context.Context, arg GetKingdomGuildInvitationParams) (int, error) {
	row := q.db.QueryRow(ctx, getKingdomGuildInvitation, arg.KingdomID, arg.GuildID)
	var id int
	err := row.Scan(&id)
	return id, err
}

const getKingdomGuildMembership = `-- name: GetKingdomGuildMembership :one
SELECT gm.id, gm.guild_id, gm.kingdom_id, gm.role, gm.joined_at, gm.created_at, g.slug AS guild_slug, g.name AS guild_name
FROM guild_memberships gm
JOIN guilds g ON g.id = gm.guild_id
WHERE gm.kingdom_id = $1
  AND gm.role IN ('applicant', 'supporter', 'member', 'officer', 'leader')
LIMIT 1
`

type GetKingdomGuildMembershipRow struct {
	ID        int
	GuildID   int
	KingdomID int
	Role      string
	JoinedAt  pgtype.Timestamptz
	CreatedAt time.Time
	GuildSlug string
	GuildName string
}

func (q *Queries) GetKingdomGuildMembership(ctx context.Context, kingdomID int) (GetKingdomGuildMembershipRow, error) {
	row := q.db.QueryRow(ctx, getKingdomGuildMembership, kingdomID)
	var i GetKingdomGuildMembershipRow
	err := row.Scan(
		&i.ID,
		&i.GuildID,
		&i.KingdomID,
		&i.Role,
		&i.JoinedAt,
		&i.CreatedAt,
		&i.GuildSlug,
		&i.GuildName,
	)
	return i, err
}

const getMembershipByID = `-- name: GetMembershipByID :one
SELECT id, guild_id, kingdom_id, role, joined_at, created_at FROM guild_memberships WHERE id = $1 AND guild_id = $2 LIMIT 1
`

type GetMembershipByIDParams struct {
	ID      int
	GuildID int
}

func (q *Queries) GetMembershipByID(ctx context.Context, arg GetMembershipByIDParams) (GuildMembership, error) {
	row := q.db.QueryRow(ctx, getMembershipByID, arg.ID, arg.GuildID)
	var i GuildMembership
	err := row.Scan(
		&i.ID,
		&i.GuildID,
		&i.KingdomID,
		&i.Role,
		&i.JoinedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getMembershipByKingdomAndGuild = `-- name: GetMembershipByKingdomAndGuild :one
SELECT id, guild_id, kingdom_id, role, joined_at, created_at FROM guild_memberships
WHERE kingdom_id = $1 AND guild_id = $2
LIMIT 1
`

type GetMembershipByKingdomAndGuildParams struct {
	KingdomID int
	GuildID   int
}

func (q *Queries) GetMembershipByKingdomAndGuild(ctx context.Context, arg GetMembershipByKingdomAndGuildParams) (GuildMembership, error) {
	row := q.db.QueryRow(ctx, getMembershipByKingdomAndGuild, arg.KingdomID, arg.GuildID)
	var i GuildMembership
	err := row.Scan(
		&i.ID,
		&i.GuildID,
		&i.KingdomID,
		&i.Role,
		&i.JoinedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveGuilds = `-- name: ListActiveGuilds :many
SELECT
    g.name,
    g.slug,
    k.name AS leader_name,
    COUNT(m.id)::int AS member_count
FROM guilds g
LEFT JOIN guild_memberships l ON l.guild_id = g.id AND l.role = 'leader'
LEFT JOIN kingdoms k ON k.id = l.kingdom_id
LEFT JOIN guild_memberships m ON m.guild_id = g.id AND m.role IN ('member', 'officer', 'leader')
WHERE g.status = 'active'
GROUP BY g.id, g.name, g.slug, k.name
ORDER BY g.name ASC
`

type ListActiveGuildsRow struct {
	Name        string
	Slug        string
	LeaderName  pgtype.Text
	MemberCount int
}

func (q *Queries) ListActiveGuilds(ctx context.Context) ([]ListActiveGuildsRow, error) {
	rows, err := q.db.Query(ctx, listActiveGuilds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveGuildsRow
	for rows.Next() {
		var i ListActiveGuildsRow
		if err := rows.Scan(
			&i.Name,
			&i.Slug,
			&i.LeaderName,
			&i.MemberCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGuildInvitations = `-- name: ListGuildInvitations :many
SELECT gm.id, gm.guild_id, gm.kingdom_id, gm.created_at,
       k.name AS kingdom_name
FROM guild_memberships gm
JOIN kingdoms k ON k.id = gm.kingdom_id
WHERE gm.guild_id = $1 AND gm.role = 'invited'
ORDER BY gm.created_at DESC
`

type ListGuildInvitationsRow struct {
	ID          int
	GuildID     int
	KingdomID   int
	CreatedAt   time.Time
	KingdomName string
}

func (q *Queries) ListGuildInvitations(ctx context.Context, guildID int) ([]ListGuildInvitationsRow, error) {
	rows, err := q.db.Query(ctx, listGuildInvitations, guildID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGuildInvitationsRow
	for rows.Next() {
		var i ListGuildInvitationsRow
		if err := rows.Scan(
			&i.ID,
			&i.GuildID,
			&i.KingdomID,
			&i.CreatedAt,
			&i.KingdomName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGuildMembersExcludingSelf = `-- name: ListGuildMembersExcludingSelf :many
SELECT kingdom_id
FROM guild_memberships
WHERE guild_id = $1
  AND kingdom_id != $2
  AND role IN ('member', 'officer', 'leader')
`

type ListGuildMembersExcludingSelfParams struct {
	GuildID          int
	ExcludeKingdomID int
}

func (q *Queries) ListGuildMembersExcludingSelf(ctx context.Context, arg ListGuildMembersExcludingSelfParams) ([]int, error) {
	rows, err := q.db.Query(ctx, listGuildMembersExcludingSelf, arg.GuildID, arg.ExcludeKingdomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int
	for rows.Next() {
		var kingdom_id int
		if err := rows.Scan(&kingdom_id); err != nil {
			return nil, err
		}
		items = append(items, kingdom_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGuildMembersWithNames = `-- name: ListGuildMembersWithNames :many
SELECT gm.id, gm.guild_id, gm.kingdom_id, gm.role, gm.joined_at, gm.created_at,
       k.name AS kingdom_name
FROM guild_memberships gm
JOIN kingdoms k ON k.id = gm.kingdom_id
WHERE gm.guild_id = $1 AND gm.role IN ('applicant', 'supporter', 'member', 'officer', 'leader')
ORDER BY
    CASE gm.role
        WHEN 'leader'    THEN 1
        WHEN 'applicant' THEN 1
        WHEN 'officer'   THEN 2
        WHEN 'member'    THEN 3
        WHEN 'supporter' THEN 4
    END,
    gm.joined_at ASC NULLS LAST,
    gm.created_at ASC
`

type ListGuildMembersWithNamesRow struct {
	ID          int
	GuildID     int
	KingdomID   int
	Role        string
	JoinedAt    pgtype.Timestamptz
	CreatedAt   time.Time
	KingdomName string
}

func (q *Queries) ListGuildMembersWithNames(ctx context.Context, guildID int) ([]ListGuildMembersWithNamesRow, error) {
	rows, err := q.db.Query(ctx, listGuildMembersWithNames, guildID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGuildMembersWithNamesRow
	for rows.Next() {
		var i ListGuildMembersWithNamesRow
		if err := rows.Scan(
			&i.ID,
			&i.GuildID,
			&i.KingdomID,
			&i.Role,
			&i.JoinedAt,
			&i.CreatedAt,
			&i.KingdomName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGuildOfficersExcludingSelf = `-- name: ListGuildOfficersExcludingSelf :many
SELECT kingdom_id
FROM guild_memberships
WHERE guild_id = $1
  AND kingdom_id != $2
  AND role IN ('officer', 'leader')
`

type ListGuildOfficersExcludingSelfParams struct {
	GuildID          int
	ExcludeKingdomID int
}

func (q *Queries) ListGuildOfficersExcludingSelf(ctx context.Context, arg ListGuildOfficersExcludingSelfParams) ([]int, error) {
	rows, err := q.db.Query(ctx, listGuildOfficersExcludingSelf, arg.GuildID, arg.ExcludeKingdomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int
	for rows.Next() {
		var kingdom_id int
		if err := rows.Scan(&kingdom_id); err != nil {
			return nil, err
		}
		items = append(items, kingdom_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listKingdomInvitations = `-- name: ListKingdomInvitations :many
SELECT gm.id, gm.guild_id, gm.kingdom_id, gm.created_at,
       g.name AS guild_name,
       g.slug AS guild_slug
FROM guild_memberships gm
JOIN guilds g ON g.id = gm.guild_id
WHERE gm.kingdom_id = $1 AND gm.role = 'invited'
ORDER BY gm.created_at DESC
`

type ListKingdomInvitationsRow struct {
	ID        int
	GuildID   int
	KingdomID int
	CreatedAt time.Time
	GuildName string
	GuildSlug string
}

func (q *Queries) ListKingdomInvitations(ctx context.Context, kingdomID int) ([]ListKingdomInvitationsRow, error) {
	rows, err := q.db.Query(ctx, listKingdomInvitations, kingdomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListKingdomInvitationsRow
	for rows.Next() {
		var i ListKingdomInvitationsRow
		if err := rows.Scan(
			&i.ID,
			&i.GuildID,
			&i.KingdomID,
			&i.CreatedAt,
			&i.GuildName,
			&i.GuildSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingGuilds = `-- name: ListPendingGuilds :many
SELECT
    g.name,
    g.slug,
    k.name AS founder_name,
    COUNT(p.id)::int AS supporter_count,
    (g.created_at + INTERVAL '7 days')::timestamptz AS expires_at
FROM guilds g
LEFT JOIN guild_memberships a ON a.guild_id = g.id AND a.role = 'applicant'
LEFT JOIN kingdoms k ON k.id = a.kingdom_id
LEFT JOIN guild_memberships p ON p.guild_id = g.id AND p.role IN ('applicant', 'supporter')
WHERE g.status = 'pending'
GROUP BY g.id, g.name, g.slug, k.name, g.created_at
ORDER BY g.name ASC
`

type ListPendingGuildsRow struct {
	Name           string
	Slug           string
	FounderName    pgtype.Text
	SupporterCount int
	ExpiresAt      time.Time
}

func (q *Queries) ListPendingGuilds(ctx context.Context) ([]ListPendingGuildsRow, error) {
	rows, err := q.db.Query(ctx, listPendingGuilds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingGuildsRow
	for rows.Next() {
		var i ListPendingGuildsRow
		if err := rows.Scan(
			&i.Name,
			&i.Slug,
			&i.FounderName,
			&i.SupporterCount,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingRequests = `-- name: ListPendingRequests :many
SELECT gm.id, gm.guild_id, gm.kingdom_id, gm.role, gm.joined_at, gm.created_at,
       k.name AS kingdom_name
FROM guild_memberships gm
JOIN kingdoms k ON k.id = gm.kingdom_id
WHERE gm.guild_id = $1 AND gm.role = 'pending_approval'
ORDER BY gm.created_at ASC
`

type ListPendingRequestsRow struct {
	ID          int
	GuildID     int
	KingdomID   int
	Role        string
	JoinedAt    pgtype.Timestamptz
	CreatedAt   time.Time
	KingdomName string
}

func (q *Queries) ListPendingRequests(ctx context.Context, guildID int) ([]ListPendingRequestsRow, error) {
	rows, err := q.db.Query(ctx, listPendingRequests, guildID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingRequestsRow
	for rows.Next() {
		var i ListPendingRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.GuildID,
			&i.KingdomID,
			&i.Role,
			&i.JoinedAt,
			&i.CreatedAt,
			&i.KingdomName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rejectMembership = `-- name: RejectMembership :exec
DELETE FROM guild_memberships
WHERE id = $1 AND guild_id = $2 AND role = 'pending_approval'
`

type RejectMembershipParams struct {
	MembershipID int
	GuildID      int
}

func (q *Queries) RejectMembership(ctx context.Context, arg RejectMembershipParams) error {
	_, err := q.db.Exec(ctx, rejectMembership, arg.MembershipID, arg.GuildID)
	return err
}

const removeMembership = `-- name: RemoveMembership :exec
DELETE FROM guild_memberships
WHERE kingdom_id = $1 AND guild_id = $2
  AND role IN ('member', 'officer', 'supporter')
`

type RemoveMembershipParams struct {
	KingdomID int
	GuildID   int
}

func (q *Queries) RemoveMembership(ctx context.Context, arg RemoveMembershipParams) error {
	_, err := q.db.Exec(ctx, removeMembership, arg.KingdomID, arg.GuildID)
	return err
}

const requestJoinIfNotFull = `-- name: RequestJoinIfNotFull :one
WITH member_count AS (
    SELECT COUNT(*) AS cnt
    FROM guild_memberships
    WHERE guild_id = $1 AND role IN ('member', 'officer', 'leader')
)
INSERT INTO guild_memberships (guild_id, kingdom_id, role)
SELECT $1, $2, 'pending_approval'
FROM member_count
WHERE cnt < 20
RETURNING id, guild_id, kingdom_id, role, joined_at, created_at
`

type RequestJoinIfNotFullParams struct {
	GuildID   int
	KingdomID int
}

// Atomically checks the active member count and inserts a pending_approval row
// in one statement. Returns no rows if the guild is full (>= 20 active members),
// which the caller maps to "this guild is full".
func (q *Queries) RequestJoinIfNotFull(ctx context.Context, arg RequestJoinIfNotFullParams) (GuildMembership, error) {
	row := q.db.QueryRow(ctx, requestJoinIfNotFull, arg.GuildID, arg.KingdomID)
	var i GuildMembership
	err := row.Scan(
		&i.ID,
		&i.GuildID,
		&i.KingdomID,
		&i.Role,
		&i.JoinedAt,
		&i.CreatedAt,
	)
	return i, err
}

const revokeGuildInvitation = `-- name: RevokeGuildInvitation :one
DELETE FROM guild_memberships WHERE id = $1 AND guild_id = $2 AND role = 'invited' RETURNING kingdom_id
`

type RevokeGuildInvitationParams struct {
	ID      int
	GuildID int
}

func (q *Queries) RevokeGuildInvitation(ctx context.Context, arg RevokeGuildInvitationParams) (int, error) {
	row := q.db.QueryRow(ctx, revokeGuildInvitation, arg.ID, arg.GuildID)
	var kingdom_id int
	err := row.Scan(&kingdom_id)
	return kingdom_id, err
}

const setMembershipRole = `-- name: SetMembershipRole :exec
UPDATE guild_memberships
SET role = $1
WHERE kingdom_id = $2 AND guild_id = $3
  AND role IN ('member', 'officer')
`

type SetMembershipRoleParams struct {
	Role      string
	KingdomID int
	GuildID   int
}

func (q *Queries) SetMembershipRole(ctx context.Context, arg SetMembershipRoleParams) error {
	_, err := q.db.Exec(ctx, setMembershipRole, arg.Role, arg.KingdomID, arg.GuildID)
	return err
}

const transferLeadership = `-- name: TransferLeadership :exec
UPDATE guild_memberships
SET role = CASE
    WHEN kingdom_id = $1::bigint THEN 'leader'
    ELSE 'member'
END
WHERE guild_id = $2
  AND (
    (kingdom_id = $1::bigint AND role IN ('member', 'officer'))
    OR role = 'leader'
  )
`

type TransferLeadershipParams struct {
	NewLeaderKingdomID int
	GuildID            int
}

func (q *Queries) TransferLeadership(ctx context.Context, arg TransferLeadershipParams) error {
	_, err := q.db.Exec(ctx, transferLeadership, arg.NewLeaderKingdomID, arg.GuildID)
	return err
}

const updateGuildDescription = `-- name: UpdateGuildDescription :exec
UPDATE guilds
SET description = $1, updated_at = NOW()
WHERE id = $2
`

type UpdateGuildDescriptionParams struct {
	Description string
	ID          int
}

func (q *Queries) UpdateGuildDescription(ctx context.Context, arg UpdateGuildDescriptionParams) error {
	_, err := q.db.Exec(ctx, updateGuildDescription, arg.Description, arg.ID)
	return err
}

const updateGuildSettings = `-- name: UpdateGuildSettings :exec
UPDATE guilds
SET settings = $1, updated_at = NOW()
WHERE id = $2
`

type UpdateGuildSettingsParams struct {
	Settings []byte
	ID       int
}

func (q *Queries) UpdateGuildSettings(ctx context.Context, arg UpdateGuildSettingsParams) error {
	_, err := q.db.Exec(ctx, updateGuildSettings, arg.Settings, arg.ID)
	return err
}

const withdrawSupport = `-- name: WithdrawSupport :exec
DELETE FROM guild_memberships
WHERE kingdom_id = $1 AND guild_id = $2 AND role = 'supporter'
`

type WithdrawSupportParams struct {
	KingdomID int
	GuildID   int
}

func (q *Queries) WithdrawSupport(ctx context.Context, arg WithdrawSupportParams) error {
	_, err := q.db.Exec(ctx, withdrawSupport, arg.KingdomID, arg.GuildID)
	return err
}
