// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: kingdom.sql

package db

import (
	"context"
)

const createKingdom = `-- name: CreateKingdom :one
INSERT INTO kingdoms (user_id, name)
VALUES ($1, $2)
RETURNING id, user_id, name, population, wood_pct, stone_pct, food_pct, mana_pct, devotion_pct, knowledge_pct, idle_pct, wood, stone, food, mana, devotion, knowledge, created_at, updated_at
`

type CreateKingdomParams struct {
	UserID int64
	Name   string
}

func (q *Queries) CreateKingdom(ctx context.Context, arg CreateKingdomParams) (Kingdom, error) {
	row := q.db.QueryRow(ctx, createKingdom, arg.UserID, arg.Name)
	var i Kingdom
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Population,
		&i.WoodPct,
		&i.StonePct,
		&i.FoodPct,
		&i.ManaPct,
		&i.DevotionPct,
		&i.KnowledgePct,
		&i.IdlePct,
		&i.Wood,
		&i.Stone,
		&i.Food,
		&i.Mana,
		&i.Devotion,
		&i.Knowledge,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getKingdomByUserID = `-- name: GetKingdomByUserID :one
SELECT id, user_id, name, population, wood_pct, stone_pct, food_pct, mana_pct, devotion_pct, knowledge_pct, idle_pct, wood, stone, food, mana, devotion, knowledge, created_at, updated_at FROM kingdoms
WHERE user_id = $1
`

func (q *Queries) GetKingdomByUserID(ctx context.Context, userID int64) (Kingdom, error) {
	row := q.db.QueryRow(ctx, getKingdomByUserID, userID)
	var i Kingdom
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Population,
		&i.WoodPct,
		&i.StonePct,
		&i.FoodPct,
		&i.ManaPct,
		&i.DevotionPct,
		&i.KnowledgePct,
		&i.IdlePct,
		&i.Wood,
		&i.Stone,
		&i.Food,
		&i.Mana,
		&i.Devotion,
		&i.Knowledge,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateKingdomAllocations = `-- name: UpdateKingdomAllocations :one
UPDATE kingdoms
SET
    wood_pct      = $2,
    stone_pct     = $3,
    food_pct      = $4,
    mana_pct      = $5,
    devotion_pct  = $6,
    knowledge_pct = $7,
    idle_pct      = $8,
    updated_at    = NOW()
WHERE user_id = $1
RETURNING id, user_id, name, population, wood_pct, stone_pct, food_pct, mana_pct, devotion_pct, knowledge_pct, idle_pct, wood, stone, food, mana, devotion, knowledge, created_at, updated_at
`

type UpdateKingdomAllocationsParams struct {
	UserID       int64
	WoodPct      int
	StonePct     int
	FoodPct      int
	ManaPct      int
	DevotionPct  int
	KnowledgePct int
	IdlePct      int
}

func (q *Queries) UpdateKingdomAllocations(ctx context.Context, arg UpdateKingdomAllocationsParams) (Kingdom, error) {
	row := q.db.QueryRow(ctx, updateKingdomAllocations,
		arg.UserID,
		arg.WoodPct,
		arg.StonePct,
		arg.FoodPct,
		arg.ManaPct,
		arg.DevotionPct,
		arg.KnowledgePct,
		arg.IdlePct,
	)
	var i Kingdom
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Population,
		&i.WoodPct,
		&i.StonePct,
		&i.FoodPct,
		&i.ManaPct,
		&i.DevotionPct,
		&i.KnowledgePct,
		&i.IdlePct,
		&i.Wood,
		&i.Stone,
		&i.Food,
		&i.Mana,
		&i.Devotion,
		&i.Knowledge,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
