// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: kingdom.sql

package db

import (
	"context"
)

const bulkGainKingdomPopulation = `-- name: BulkGainKingdomPopulation :exec
UPDATE kingdoms
SET population = population + data.gain
FROM (
    SELECT unnest($1::bigint[]) AS id,
           unnest($2::int[])  AS gain
) AS data
WHERE kingdoms.id = data.id
`

type BulkGainKingdomPopulationParams struct {
	Ids   []int
	Gains []int
}

func (q *Queries) BulkGainKingdomPopulation(ctx context.Context, arg BulkGainKingdomPopulationParams) error {
	_, err := q.db.Exec(ctx, bulkGainKingdomPopulation, arg.Ids, arg.Gains)
	return err
}

const bulkTickKingdoms = `-- name: BulkTickKingdoms :exec
UPDATE kingdoms
SET
    wood       = new.wood,
    stone      = new.stone,
    food       = new.food,
    mana       = new.mana,
    devotion   = new.devotion,
    knowledge  = new.knowledge,
    population = new.population,
    updated_at = NOW()
FROM (
    SELECT
        unnest($1::bigint[])        AS id,
        unnest($2::bigint[])       AS wood,
        unnest($3::bigint[])      AS stone,
        unnest($4::bigint[])       AS food,
        unnest($5::bigint[])       AS mana,
        unnest($6::bigint[])   AS devotion,
        unnest($7::bigint[])  AS knowledge,
        unnest($8::bigint[]) AS population
) AS new
WHERE kingdoms.id = new.id
`

type BulkTickKingdomsParams struct {
	Ids        []int
	Wood       []int
	Stone      []int
	Food       []int
	Mana       []int
	Devotion   []int
	Knowledge  []int
	Population []int
}

func (q *Queries) BulkTickKingdoms(ctx context.Context, arg BulkTickKingdomsParams) error {
	_, err := q.db.Exec(ctx, bulkTickKingdoms,
		arg.Ids,
		arg.Wood,
		arg.Stone,
		arg.Food,
		arg.Mana,
		arg.Devotion,
		arg.Knowledge,
		arg.Population,
	)
	return err
}

const createKingdom = `-- name: CreateKingdom :one
INSERT INTO kingdoms (user_id, name, x, y)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, name, population, wood_pct, stone_pct, food_pct, mana_pct, devotion_pct, knowledge_pct, idle_pct, wood, stone, food, mana, devotion, knowledge, created_at, updated_at, x, y
`

type CreateKingdomParams struct {
	UserID int
	Name   string
	X      int
	Y      int
}

func (q *Queries) CreateKingdom(ctx context.Context, arg CreateKingdomParams) (Kingdom, error) {
	row := q.db.QueryRow(ctx, createKingdom,
		arg.UserID,
		arg.Name,
		arg.X,
		arg.Y,
	)
	var i Kingdom
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Population,
		&i.WoodPct,
		&i.StonePct,
		&i.FoodPct,
		&i.ManaPct,
		&i.DevotionPct,
		&i.KnowledgePct,
		&i.IdlePct,
		&i.Wood,
		&i.Stone,
		&i.Food,
		&i.Mana,
		&i.Devotion,
		&i.Knowledge,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.X,
		&i.Y,
	)
	return i, err
}

const getKingdomByID = `-- name: GetKingdomByID :one
SELECT id, user_id, name, population, wood_pct, stone_pct, food_pct, mana_pct, devotion_pct, knowledge_pct, idle_pct, wood, stone, food, mana, devotion, knowledge, created_at, updated_at, x, y FROM kingdoms
WHERE id = $1
`

func (q *Queries) GetKingdomByID(ctx context.Context, id int) (Kingdom, error) {
	row := q.db.QueryRow(ctx, getKingdomByID, id)
	var i Kingdom
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Population,
		&i.WoodPct,
		&i.StonePct,
		&i.FoodPct,
		&i.ManaPct,
		&i.DevotionPct,
		&i.KnowledgePct,
		&i.IdlePct,
		&i.Wood,
		&i.Stone,
		&i.Food,
		&i.Mana,
		&i.Devotion,
		&i.Knowledge,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.X,
		&i.Y,
	)
	return i, err
}

const getKingdomByName = `-- name: GetKingdomByName :one
SELECT id, user_id, name, population, wood_pct, stone_pct, food_pct, mana_pct, devotion_pct, knowledge_pct, idle_pct, wood, stone, food, mana, devotion, knowledge, created_at, updated_at, x, y FROM kingdoms
WHERE name = $1
`

func (q *Queries) GetKingdomByName(ctx context.Context, name string) (Kingdom, error) {
	row := q.db.QueryRow(ctx, getKingdomByName, name)
	var i Kingdom
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Population,
		&i.WoodPct,
		&i.StonePct,
		&i.FoodPct,
		&i.ManaPct,
		&i.DevotionPct,
		&i.KnowledgePct,
		&i.IdlePct,
		&i.Wood,
		&i.Stone,
		&i.Food,
		&i.Mana,
		&i.Devotion,
		&i.Knowledge,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.X,
		&i.Y,
	)
	return i, err
}

const getKingdomByUserID = `-- name: GetKingdomByUserID :one
SELECT id, user_id, name, population, wood_pct, stone_pct, food_pct, mana_pct, devotion_pct, knowledge_pct, idle_pct, wood, stone, food, mana, devotion, knowledge, created_at, updated_at, x, y FROM kingdoms
WHERE user_id = $1
`

func (q *Queries) GetKingdomByUserID(ctx context.Context, userID int) (Kingdom, error) {
	row := q.db.QueryRow(ctx, getKingdomByUserID, userID)
	var i Kingdom
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Population,
		&i.WoodPct,
		&i.StonePct,
		&i.FoodPct,
		&i.ManaPct,
		&i.DevotionPct,
		&i.KnowledgePct,
		&i.IdlePct,
		&i.Wood,
		&i.Stone,
		&i.Food,
		&i.Mana,
		&i.Devotion,
		&i.Knowledge,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.X,
		&i.Y,
	)
	return i, err
}

const getKingdomsByIDs = `-- name: GetKingdomsByIDs :many
SELECT id, user_id, name, population, wood_pct, stone_pct, food_pct, mana_pct, devotion_pct, knowledge_pct, idle_pct, wood, stone, food, mana, devotion, knowledge, created_at, updated_at, x, y FROM kingdoms
WHERE id = ANY($1::bigint[])
`

func (q *Queries) GetKingdomsByIDs(ctx context.Context, ids []int) ([]Kingdom, error) {
	rows, err := q.db.Query(ctx, getKingdomsByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Kingdom
	for rows.Next() {
		var i Kingdom
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Population,
			&i.WoodPct,
			&i.StonePct,
			&i.FoodPct,
			&i.ManaPct,
			&i.DevotionPct,
			&i.KnowledgePct,
			&i.IdlePct,
			&i.Wood,
			&i.Stone,
			&i.Food,
			&i.Mana,
			&i.Devotion,
			&i.Knowledge,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.X,
			&i.Y,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getKingdomsByNames = `-- name: GetKingdomsByNames :many
SELECT id, user_id, name, population, wood_pct, stone_pct, food_pct, mana_pct, devotion_pct, knowledge_pct, idle_pct, wood, stone, food, mana, devotion, knowledge, created_at, updated_at, x, y FROM kingdoms
WHERE name = ANY($1::citext[])
`

func (q *Queries) GetKingdomsByNames(ctx context.Context, names []string) ([]Kingdom, error) {
	rows, err := q.db.Query(ctx, getKingdomsByNames, names)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Kingdom
	for rows.Next() {
		var i Kingdom
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Population,
			&i.WoodPct,
			&i.StonePct,
			&i.FoodPct,
			&i.ManaPct,
			&i.DevotionPct,
			&i.KnowledgePct,
			&i.IdlePct,
			&i.Wood,
			&i.Stone,
			&i.Food,
			&i.Mana,
			&i.Devotion,
			&i.Knowledge,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.X,
			&i.Y,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getKingdomsInViewport = `-- name: GetKingdomsInViewport :many
SELECT id, name, x, y FROM kingdoms
WHERE x >= $1 AND x <= $2
  AND y >= $3 AND y <= $4
`

type GetKingdomsInViewportParams struct {
	X   int
	X_2 int
	Y   int
	Y_2 int
}

type GetKingdomsInViewportRow struct {
	ID   int
	Name string
	X    int
	Y    int
}

func (q *Queries) GetKingdomsInViewport(ctx context.Context, arg GetKingdomsInViewportParams) ([]GetKingdomsInViewportRow, error) {
	rows, err := q.db.Query(ctx, getKingdomsInViewport,
		arg.X,
		arg.X_2,
		arg.Y,
		arg.Y_2,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetKingdomsInViewportRow
	for rows.Next() {
		var i GetKingdomsInViewportRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.X,
			&i.Y,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllKingdoms = `-- name: ListAllKingdoms :many
SELECT id, user_id, name, population, wood_pct, stone_pct, food_pct, mana_pct, devotion_pct, knowledge_pct, idle_pct, wood, stone, food, mana, devotion, knowledge, created_at, updated_at, x, y FROM kingdoms
`

func (q *Queries) ListAllKingdoms(ctx context.Context) ([]Kingdom, error) {
	rows, err := q.db.Query(ctx, listAllKingdoms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Kingdom
	for rows.Next() {
		var i Kingdom
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Population,
			&i.WoodPct,
			&i.StonePct,
			&i.FoodPct,
			&i.ManaPct,
			&i.DevotionPct,
			&i.KnowledgePct,
			&i.IdlePct,
			&i.Wood,
			&i.Stone,
			&i.Food,
			&i.Mana,
			&i.Devotion,
			&i.Knowledge,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.X,
			&i.Y,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOtherKingdoms = `-- name: ListOtherKingdoms :many
SELECT id, name FROM kingdoms
WHERE id != $1
ORDER BY name
`

type ListOtherKingdomsRow struct {
	ID   int
	Name string
}

func (q *Queries) ListOtherKingdoms(ctx context.Context, id int) ([]ListOtherKingdomsRow, error) {
	rows, err := q.db.Query(ctx, listOtherKingdoms, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOtherKingdomsRow
	for rows.Next() {
		var i ListOtherKingdomsRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const stealKingdomPopulation = `-- name: StealKingdomPopulation :exec
UPDATE kingdoms
SET population = GREATEST($1, population - $2)
WHERE id = $3
`

type StealKingdomPopulationParams struct {
	MinPopulation int
	Amount        int
	ID            int
}

// The floor is a parameter so game.MinPopulation stays the single source of
// truth instead of being hardcoded here.
func (q *Queries) StealKingdomPopulation(ctx context.Context, arg StealKingdomPopulationParams) error {
	_, err := q.db.Exec(ctx, stealKingdomPopulation, arg.MinPopulation, arg.Amount, arg.ID)
	return err
}

const updateKingdomAllocations = `-- name: UpdateKingdomAllocations :one
UPDATE kingdoms
SET
    wood_pct      = $1,
    stone_pct     = $2,
    food_pct      = $3,
    mana_pct      = $4,
    devotion_pct  = $5,
    knowledge_pct = $6,
    idle_pct      = $7,
    updated_at    = NOW()
WHERE user_id = $8
RETURNING id, user_id, name, population, wood_pct, stone_pct, food_pct, mana_pct, devotion_pct, knowledge_pct, idle_pct, wood, stone, food, mana, devotion, knowledge, created_at, updated_at, x, y
`

type UpdateKingdomAllocationsParams struct {
	WoodPct      int
	StonePct     int
	FoodPct      int
	ManaPct      int
	DevotionPct  int
	KnowledgePct int
	IdlePct      int
	UserID       int
}

func (q *Queries) UpdateKingdomAllocations(ctx context.Context, arg UpdateKingdomAllocationsParams) (Kingdom, error) {
	row := q.db.QueryRow(ctx, updateKingdomAllocations,
		arg.WoodPct,
		arg.StonePct,
		arg.FoodPct,
		arg.ManaPct,
		arg.DevotionPct,
		arg.KnowledgePct,
		arg.IdlePct,
		arg.UserID,
	)
	var i Kingdom
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Population,
		&i.WoodPct,
		&i.StonePct,
		&i.FoodPct,
		&i.ManaPct,
		&i.DevotionPct,
		&i.KnowledgePct,
		&i.IdlePct,
		&i.Wood,
		&i.Stone,
		&i.Food,
		&i.Mana,
		&i.Devotion,
		&i.Knowledge,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.X,
		&i.Y,
	)
	return i, err
}
