// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: legions.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const bulkDeleteLegionUnitsZero = `-- name: BulkDeleteLegionUnitsZero :exec
DELETE FROM kingdom_legion_units
WHERE (legion_id, unit_type) IN (
    SELECT unnest($1::bigint[]), unnest($2::text[])
)
`

type BulkDeleteLegionUnitsZeroParams struct {
	LegionIds []int
	UnitTypes []string
}

func (q *Queries) BulkDeleteLegionUnitsZero(ctx context.Context, arg BulkDeleteLegionUnitsZeroParams) error {
	_, err := q.db.Exec(ctx, bulkDeleteLegionUnitsZero, arg.LegionIds, arg.UnitTypes)
	return err
}

const bulkUpdateLegionUnitCounts = `-- name: BulkUpdateLegionUnitCounts :exec
UPDATE kingdom_legion_units
SET count = data.count
FROM (
    SELECT
        unnest($1::bigint[]) AS legion_id,
        unnest($2::text[])   AS unit_type,
        unnest($3::int[])        AS count
) AS data
WHERE kingdom_legion_units.legion_id = data.legion_id
  AND kingdom_legion_units.unit_type = data.unit_type
`

type BulkUpdateLegionUnitCountsParams struct {
	LegionIds []int
	UnitTypes []string
	Counts    []int
}

func (q *Queries) BulkUpdateLegionUnitCounts(ctx context.Context, arg BulkUpdateLegionUnitCountsParams) error {
	_, err := q.db.Exec(ctx, bulkUpdateLegionUnitCounts, arg.LegionIds, arg.UnitTypes, arg.Counts)
	return err
}

const clearLegionUnits = `-- name: ClearLegionUnits :exec
DELETE FROM kingdom_legion_units WHERE legion_id = $1
`

func (q *Queries) ClearLegionUnits(ctx context.Context, legionID int) error {
	_, err := q.db.Exec(ctx, clearLegionUnits, legionID)
	return err
}

const countLegionsForKingdom = `-- name: CountLegionsForKingdom :one
SELECT COUNT(*) FROM kingdom_legions WHERE kingdom_id = $1
`

func (q *Queries) CountLegionsForKingdom(ctx context.Context, kingdomID int) (int, error) {
	row := q.db.QueryRow(ctx, countLegionsForKingdom, kingdomID)
	var count int
	err := row.Scan(&count)
	return count, err
}

const createLegion = `-- name: CreateLegion :one
INSERT INTO kingdom_legions (kingdom_id, number, name)
SELECT $1, s, 'Legion ' || s
FROM generate_series(1, $2::int) s
WHERE s NOT IN (
    SELECT number FROM kingdom_legions WHERE kingdom_id = $1
)
ORDER BY s
LIMIT 1
RETURNING id, kingdom_id, number, name, created_at
`

type CreateLegionParams struct {
	KingdomID int
	Cap       int
}

func (q *Queries) CreateLegion(ctx context.Context, arg CreateLegionParams) (KingdomLegion, error) {
	row := q.db.QueryRow(ctx, createLegion, arg.KingdomID, arg.Cap)
	var i KingdomLegion
	err := row.Scan(
		&i.ID,
		&i.KingdomID,
		&i.Number,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const decrementLegionUnit = `-- name: DecrementLegionUnit :exec
WITH updated AS (
    UPDATE kingdom_legion_units
    SET count = count - $3::int
    WHERE legion_id = $1 AND unit_type = $2
      AND count - $3 > 0
    RETURNING legion_id, unit_type
)
DELETE FROM kingdom_legion_units AS klu
WHERE klu.legion_id = $1
  AND klu.unit_type = $2
  AND NOT EXISTS (SELECT 1 FROM updated)
`

type DecrementLegionUnitParams struct {
	LegionID int
	UnitType string
	Amount   int
}

func (q *Queries) DecrementLegionUnit(ctx context.Context, arg DecrementLegionUnitParams) error {
	_, err := q.db.Exec(ctx, decrementLegionUnit, arg.LegionID, arg.UnitType, arg.Amount)
	return err
}

const deleteLegion = `-- name: DeleteLegion :exec
DELETE FROM kingdom_legions WHERE id = $1 AND kingdom_id = $2
`

type DeleteLegionParams struct {
	ID        int
	KingdomID int
}

func (q *Queries) DeleteLegion(ctx context.Context, arg DeleteLegionParams) error {
	_, err := q.db.Exec(ctx, deleteLegion, arg.ID, arg.KingdomID)
	return err
}

const getAtHomeLegionUnitsByKingdomIDs = `-- name: GetAtHomeLegionUnitsByKingdomIDs :many
SELECT klu.legion_id, kl.kingdom_id, klu.unit_type, klu.count
FROM kingdom_legion_units klu
JOIN kingdom_legions kl ON kl.id = klu.legion_id
WHERE kl.kingdom_id = ANY($1::bigint[])
  AND NOT EXISTS (
      SELECT 1 FROM kingdom_campaigns kc WHERE kc.legion_id = klu.legion_id
  )
`

type GetAtHomeLegionUnitsByKingdomIDsRow struct {
	LegionID  int
	KingdomID int
	UnitType  string
	Count     int
}

func (q *Queries) GetAtHomeLegionUnitsByKingdomIDs(ctx context.Context, ids []int) ([]GetAtHomeLegionUnitsByKingdomIDsRow, error) {
	rows, err := q.db.Query(ctx, getAtHomeLegionUnitsByKingdomIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAtHomeLegionUnitsByKingdomIDsRow
	for rows.Next() {
		var i GetAtHomeLegionUnitsByKingdomIDsRow
		if err := rows.Scan(
			&i.LegionID,
			&i.KingdomID,
			&i.UnitType,
			&i.Count,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLegion = `-- name: GetLegion :one
SELECT id, kingdom_id, number, name, created_at FROM kingdom_legions
WHERE id = $1 AND kingdom_id = $2
`

type GetLegionParams struct {
	ID        int
	KingdomID int
}

func (q *Queries) GetLegion(ctx context.Context, arg GetLegionParams) (KingdomLegion, error) {
	row := q.db.QueryRow(ctx, getLegion, arg.ID, arg.KingdomID)
	var i KingdomLegion
	err := row.Scan(
		&i.ID,
		&i.KingdomID,
		&i.Number,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const getLegionForUpdate = `-- name: GetLegionForUpdate :one
SELECT id, kingdom_id, number, name, created_at FROM kingdom_legions
WHERE id = $1 AND kingdom_id = $2
FOR UPDATE
`

type GetLegionForUpdateParams struct {
	ID        int
	KingdomID int
}

func (q *Queries) GetLegionForUpdate(ctx context.Context, arg GetLegionForUpdateParams) (KingdomLegion, error) {
	row := q.db.QueryRow(ctx, getLegionForUpdate, arg.ID, arg.KingdomID)
	var i KingdomLegion
	err := row.Scan(
		&i.ID,
		&i.KingdomID,
		&i.Number,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const listAllLegionUnitsForKingdom = `-- name: ListAllLegionUnitsForKingdom :many
SELECT klu.legion_id, klu.unit_type, klu.count
FROM kingdom_legion_units klu
JOIN kingdom_legions kl ON kl.id = klu.legion_id
WHERE kl.kingdom_id = $1
ORDER BY klu.legion_id, klu.unit_type
`

func (q *Queries) ListAllLegionUnitsForKingdom(ctx context.Context, kingdomID int) ([]KingdomLegionUnit, error) {
	rows, err := q.db.Query(ctx, listAllLegionUnitsForKingdom, kingdomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []KingdomLegionUnit
	for rows.Next() {
		var i KingdomLegionUnit
		if err := rows.Scan(&i.LegionID, &i.UnitType, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLegionUnits = `-- name: ListLegionUnits :many
SELECT legion_id, unit_type, count FROM kingdom_legion_units WHERE legion_id = $1
`

func (q *Queries) ListLegionUnits(ctx context.Context, legionID int) ([]KingdomLegionUnit, error) {
	rows, err := q.db.Query(ctx, listLegionUnits, legionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []KingdomLegionUnit
	for rows.Next() {
		var i KingdomLegionUnit
		if err := rows.Scan(&i.LegionID, &i.UnitType, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLegionsForKingdom = `-- name: ListLegionsForKingdom :many
SELECT
    kl.id,
    kl.kingdom_id,
    kl.number,
    kl.name,
    kl.created_at,
    kc.status AS campaign_status
FROM kingdom_legions kl
LEFT JOIN kingdom_campaigns kc ON kc.legion_id = kl.id
WHERE kl.kingdom_id = $1
ORDER BY kl.number
`

type ListLegionsForKingdomRow struct {
	ID             int
	KingdomID      int
	Number         int
	Name           string
	CreatedAt      time.Time
	CampaignStatus pgtype.Text
}

func (q *Queries) ListLegionsForKingdom(ctx context.Context, kingdomID int) ([]ListLegionsForKingdomRow, error) {
	rows, err := q.db.Query(ctx, listLegionsForKingdom, kingdomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLegionsForKingdomRow
	for rows.Next() {
		var i ListLegionsForKingdomRow
		if err := rows.Scan(
			&i.ID,
			&i.KingdomID,
			&i.Number,
			&i.Name,
			&i.CreatedAt,
			&i.CampaignStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertLegionUnit = `-- name: UpsertLegionUnit :exec
INSERT INTO kingdom_legion_units (legion_id, unit_type, count)
VALUES ($1, $2, $3)
ON CONFLICT (legion_id, unit_type)
DO UPDATE SET count = kingdom_legion_units.count + EXCLUDED.count
`

type UpsertLegionUnitParams struct {
	LegionID int
	UnitType string
	Count    int
}

func (q *Queries) UpsertLegionUnit(ctx context.Context, arg UpsertLegionUnitParams) error {
	_, err := q.db.Exec(ctx, upsertLegionUnit, arg.LegionID, arg.UnitType, arg.Count)
	return err
}
