// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: messages.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const bulkCreateMessages = `-- name: BulkCreateMessages :exec
INSERT INTO kingdom_messages (from_kingdom_id, to_kingdom_id, subject, body, action_url, action_text, is_guild_message)
SELECT $1::bigint, unnest($2::bigint[]), $3::text, $4::text, $5::text, $6::text, $7::boolean
`

type BulkCreateMessagesParams struct {
	FromKingdomID  int
	ToKingdomIds   []int
	Subject        string
	Body           string
	ActionUrl      string
	ActionText     string
	IsGuildMessage bool
}

func (q *Queries) BulkCreateMessages(ctx context.Context, arg BulkCreateMessagesParams) error {
	_, err := q.db.Exec(ctx, bulkCreateMessages,
		arg.FromKingdomID,
		arg.ToKingdomIds,
		arg.Subject,
		arg.Body,
		arg.ActionUrl,
		arg.ActionText,
		arg.IsGuildMessage,
	)
	return err
}

const countUnreadMessages = `-- name: CountUnreadMessages :one
SELECT COUNT(*)
FROM kingdom_messages
WHERE to_kingdom_id = $1
  AND read_at IS NULL
  AND deleted_at IS NULL
`

func (q *Queries) CountUnreadMessages(ctx context.Context, toKingdomID int) (int, error) {
	row := q.db.QueryRow(ctx, countUnreadMessages, toKingdomID)
	var count int
	err := row.Scan(&count)
	return count, err
}

const deleteMessage = `-- name: DeleteMessage :exec
UPDATE kingdom_messages
SET deleted_at = NOW()
WHERE id = $1
  AND to_kingdom_id = $2
`

type DeleteMessageParams struct {
	ID          int
	ToKingdomID int
}

func (q *Queries) DeleteMessage(ctx context.Context, arg DeleteMessageParams) error {
	_, err := q.db.Exec(ctx, deleteMessage, arg.ID, arg.ToKingdomID)
	return err
}

const deleteMessages = `-- name: DeleteMessages :exec
UPDATE kingdom_messages
SET deleted_at = NOW()
WHERE id = ANY($1::bigint[])
  AND to_kingdom_id = $2
`

type DeleteMessagesParams struct {
	Ids         []int
	ToKingdomID int
}

func (q *Queries) DeleteMessages(ctx context.Context, arg DeleteMessagesParams) error {
	_, err := q.db.Exec(ctx, deleteMessages, arg.Ids, arg.ToKingdomID)
	return err
}

const getInboxMessageByID = `-- name: GetInboxMessageByID :one
SELECT
    m.id,
    m.from_kingdom_id,
    m.to_kingdom_id,
    m.subject,
    m.body,
    m.action_url,
    m.action_text,
    m.read_at,
    m.created_at,
    fk.name AS from_kingdom_name,
    tk.name AS to_kingdom_name
FROM kingdom_messages m
JOIN kingdoms fk ON fk.id = m.from_kingdom_id
JOIN kingdoms tk ON tk.id = m.to_kingdom_id
WHERE m.id = $1
  AND m.to_kingdom_id = $2
  AND m.deleted_at IS NULL
`

type GetInboxMessageByIDParams struct {
	ID          int
	ToKingdomID int
}

type GetInboxMessageByIDRow struct {
	ID              int
	FromKingdomID   int
	ToKingdomID     int
	Subject         string
	Body            string
	ActionUrl       pgtype.Text
	ActionText      pgtype.Text
	ReadAt          pgtype.Timestamptz
	CreatedAt       time.Time
	FromKingdomName string
	ToKingdomName   string
}

func (q *Queries) GetInboxMessageByID(ctx context.Context, arg GetInboxMessageByIDParams) (GetInboxMessageByIDRow, error) {
	row := q.db.QueryRow(ctx, getInboxMessageByID, arg.ID, arg.ToKingdomID)
	var i GetInboxMessageByIDRow
	err := row.Scan(
		&i.ID,
		&i.FromKingdomID,
		&i.ToKingdomID,
		&i.Subject,
		&i.Body,
		&i.ActionUrl,
		&i.ActionText,
		&i.ReadAt,
		&i.CreatedAt,
		&i.FromKingdomName,
		&i.ToKingdomName,
	)
	return i, err
}

const listInboxMessages = `-- name: ListInboxMessages :many
SELECT
    m.id,
    m.from_kingdom_id,
    m.to_kingdom_id,
    m.subject,
    m.body,
    m.read_at,
    m.created_at,
    fk.name AS from_kingdom_name
FROM kingdom_messages m
JOIN kingdoms fk ON fk.id = m.from_kingdom_id
WHERE m.to_kingdom_id = $1
  AND m.deleted_at IS NULL
ORDER BY m.created_at DESC
LIMIT 50
`

type ListInboxMessagesRow struct {
	ID              int
	FromKingdomID   int
	ToKingdomID     int
	Subject         string
	Body            string
	ReadAt          pgtype.Timestamptz
	CreatedAt       time.Time
	FromKingdomName string
}

func (q *Queries) ListInboxMessages(ctx context.Context, toKingdomID int) ([]ListInboxMessagesRow, error) {
	rows, err := q.db.Query(ctx, listInboxMessages, toKingdomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListInboxMessagesRow
	for rows.Next() {
		var i ListInboxMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.FromKingdomID,
			&i.ToKingdomID,
			&i.Subject,
			&i.Body,
			&i.ReadAt,
			&i.CreatedAt,
			&i.FromKingdomName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markMessageRead = `-- name: MarkMessageRead :exec
UPDATE kingdom_messages
SET read_at = NOW()
WHERE id = $1
  AND to_kingdom_id = $2
  AND read_at IS NULL
`

type MarkMessageReadParams struct {
	ID          int
	ToKingdomID int
}

func (q *Queries) MarkMessageRead(ctx context.Context, arg MarkMessageReadParams) error {
	_, err := q.db.Exec(ctx, markMessageRead, arg.ID, arg.ToKingdomID)
	return err
}
