// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"net/netip"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type EmailVerificationToken struct {
	Token     string
	UserID    int64
	ExpiresAt time.Time
	CreatedAt time.Time
}

type Kingdom struct {
	ID           int64
	UserID       int64
	Name         string
	Population   int64
	WoodPct      int
	StonePct     int
	FoodPct      int
	ManaPct      int
	DevotionPct  int
	KnowledgePct int
	IdlePct      int
	Wood         int64
	Stone        int64
	Food         int64
	Mana         int64
	Devotion     int64
	Knowledge    int64
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type PasswordResetToken struct {
	Token     string
	UserID    int64
	ExpiresAt time.Time
	CreatedAt time.Time
}

type Session struct {
	ID        string
	UserID    int64
	IpAddress netip.Addr
	UserAgent string
	ExpiresAt time.Time
	CreatedAt time.Time
}

type User struct {
	ID          int64
	Email       string
	PwHash      string
	IsActive    bool
	IsVerified  bool
	CreatedAt   time.Time
	UpdatedAt   time.Time
	LastLoginAt pgtype.Timestamptz
}
