// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"net/netip"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type EmailVerificationToken struct {
	Token     string
	UserID    int
	ExpiresAt time.Time
	CreatedAt time.Time
}

type GameTick struct {
	ID         int
	OccurredAt time.Time
}

type Guild struct {
	ID                 int
	Name               string
	Slug               string
	Description        string
	Status             string
	FoundingKingdomIds []int
	CreatedAt          time.Time
	UpdatedAt          time.Time
	Settings           []byte
}

type GuildMembership struct {
	ID        int
	GuildID   int
	KingdomID int
	Role      string
	JoinedAt  pgtype.Timestamptz
	CreatedAt time.Time
}

type Kingdom struct {
	ID           int
	UserID       int
	Name         string
	Population   int
	WoodPct      int
	StonePct     int
	FoodPct      int
	ManaPct      int
	DevotionPct  int
	KnowledgePct int
	IdlePct      int
	Wood         int
	Stone        int
	Food         int
	Mana         int
	Devotion     int
	Knowledge    int
	CreatedAt    time.Time
	UpdatedAt    time.Time
	X            int
	Y            int
}

type KingdomAvailableUnit struct {
	KingdomID int
	UnitType  string
	Count     int
}

type KingdomBuilding struct {
	KingdomID    int
	BuildingType string
	Count        int
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type KingdomCampaign struct {
	ID              int
	KingdomID       int
	TargetKingdomID int
	UnitType        string
	Count           int
	Action          string
	Status          string
	TicksRemaining  int
	ActionTicks     int
	TravelTicks     int
	CreatedAt       time.Time
}

type KingdomCombatLog struct {
	ID                 int
	TickID             int
	TargetKingdomID    int
	AttackerUnits      []byte
	DefenderUnits      []byte
	AttackerPower      int
	DefenderPower      int
	Winner             string
	AttackerCasualties int
	DefenderCasualties int
	PopulationStolen   int
	OccurredAt         time.Time
}

type KingdomCombatLogParticipant struct {
	CombatLogID      int
	KingdomID        int
	Role             string
	PopulationGained int
}

type KingdomConstruction struct {
	ID             int
	KingdomID      int
	BuildingType   string
	TicksRemaining int
	TicksTotal     int
	StartedAt      time.Time
}

type KingdomMessage struct {
	ID             int
	FromKingdomID  int
	ToKingdomID    int
	Subject        string
	Body           string
	ReadAt         pgtype.Timestamptz
	DeletedAt      pgtype.Timestamptz
	CreatedAt      time.Time
	ActionUrl      pgtype.Text
	ActionText     pgtype.Text
	IsGuildMessage bool
}

type KingdomPrayer struct {
	ID              int
	KingdomID       int
	TargetKingdomID int
	PrayerType      string
	TicksRemaining  int
	TicksTotal      int
	StartedAt       time.Time
}

type KingdomTraining struct {
	ID             int
	KingdomID      int
	UnitType       string
	Count          int
	TicksRemaining int
	TicksTotal     int
	StartedAt      time.Time
}

type KingdomUnit struct {
	KingdomID int
	UnitType  string
	Count     int
	CreatedAt time.Time
	UpdatedAt time.Time
}

type PasswordResetToken struct {
	Token     string
	UserID    int
	ExpiresAt time.Time
	CreatedAt time.Time
}

type Session struct {
	ID        string
	UserID    int
	IpAddress netip.Addr
	UserAgent string
	ExpiresAt time.Time
	CreatedAt time.Time
}

type User struct {
	ID          int
	Email       string
	PwHash      string
	IsActive    bool
	IsVerified  bool
	CreatedAt   time.Time
	UpdatedAt   time.Time
	LastLoginAt pgtype.Timestamptz
}
