// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"net/netip"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type EmailVerificationToken struct {
	Token     string
	UserID    int
	ExpiresAt time.Time
	CreatedAt time.Time
}

type Kingdom struct {
	ID           int
	UserID       int
	Name         string
	Population   int
	WoodPct      int
	StonePct     int
	FoodPct      int
	ManaPct      int
	DevotionPct  int
	KnowledgePct int
	IdlePct      int
	Wood         int
	Stone        int
	Food         int
	Mana         int
	Devotion     int
	Knowledge    int
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type KingdomBuilding struct {
	KingdomID    int
	BuildingType string
	Count        int
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type KingdomConstruction struct {
	ID             int
	KingdomID      int
	BuildingType   string
	TicksRemaining int
	TicksTotal     int
	StartedAt      time.Time
}

type PasswordResetToken struct {
	Token     string
	UserID    int
	ExpiresAt time.Time
	CreatedAt time.Time
}

type Session struct {
	ID        string
	UserID    int
	IpAddress netip.Addr
	UserAgent string
	ExpiresAt time.Time
	CreatedAt time.Time
}

type User struct {
	ID          int
	Email       string
	PwHash      string
	IsActive    bool
	IsVerified  bool
	CreatedAt   time.Time
	UpdatedAt   time.Time
	LastLoginAt pgtype.Timestamptz
}
