// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: prayers.sql

package db

import (
	"context"
	"time"
)

const createPrayer = `-- name: CreatePrayer :one
INSERT INTO kingdom_prayers (kingdom_id, prayer_type, target_kingdom_id, ticks_remaining, ticks_total)
VALUES ($1, $2, $3, $4, $4)
RETURNING id, kingdom_id, target_kingdom_id, prayer_type, ticks_remaining, ticks_total, started_at
`

type CreatePrayerParams struct {
	KingdomID       int
	PrayerType      string
	TargetKingdomID int
	TicksTotal      int
}

func (q *Queries) CreatePrayer(ctx context.Context, arg CreatePrayerParams) (KingdomPrayer, error) {
	row := q.db.QueryRow(ctx, createPrayer,
		arg.KingdomID,
		arg.PrayerType,
		arg.TargetKingdomID,
		arg.TicksTotal,
	)
	var i KingdomPrayer
	err := row.Scan(
		&i.ID,
		&i.KingdomID,
		&i.TargetKingdomID,
		&i.PrayerType,
		&i.TicksRemaining,
		&i.TicksTotal,
		&i.StartedAt,
	)
	return i, err
}

const decrementAndListPrayersAtZero = `-- name: DecrementAndListPrayersAtZero :many
WITH expired AS (
    DELETE FROM kingdom_prayers
    WHERE ticks_remaining = 1
    RETURNING id, kingdom_id, target_kingdom_id, prayer_type, ticks_remaining, ticks_total, started_at
),
decremented AS (
    UPDATE kingdom_prayers
    SET ticks_remaining = ticks_remaining - 1
    WHERE ticks_remaining > 1
)
SELECT id, kingdom_id, target_kingdom_id, prayer_type, ticks_remaining, ticks_total, started_at FROM expired
`

type DecrementAndListPrayersAtZeroRow struct {
	ID              int
	KingdomID       int
	TargetKingdomID int
	PrayerType      string
	TicksRemaining  int
	TicksTotal      int
	StartedAt       time.Time
}

func (q *Queries) DecrementAndListPrayersAtZero(ctx context.Context) ([]DecrementAndListPrayersAtZeroRow, error) {
	rows, err := q.db.Query(ctx, decrementAndListPrayersAtZero)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DecrementAndListPrayersAtZeroRow
	for rows.Next() {
		var i DecrementAndListPrayersAtZeroRow
		if err := rows.Scan(
			&i.ID,
			&i.KingdomID,
			&i.TargetKingdomID,
			&i.PrayerType,
			&i.TicksRemaining,
			&i.TicksTotal,
			&i.StartedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteKingdomPrayers = `-- name: DeleteKingdomPrayers :exec
DELETE FROM kingdom_prayers
WHERE kingdom_id = ANY($1::bigint[])
`

func (q *Queries) DeleteKingdomPrayers(ctx context.Context, ids []int) error {
	_, err := q.db.Exec(ctx, deleteKingdomPrayers, ids)
	return err
}

const deletePrayer = `-- name: DeletePrayer :exec
DELETE FROM kingdom_prayers
WHERE id = $1 AND kingdom_id = $2
`

type DeletePrayerParams struct {
	ID        int
	KingdomID int
}

func (q *Queries) DeletePrayer(ctx context.Context, arg DeletePrayerParams) error {
	_, err := q.db.Exec(ctx, deletePrayer, arg.ID, arg.KingdomID)
	return err
}

const getAllKingdomPrayers = `-- name: GetAllKingdomPrayers :many
SELECT id, kingdom_id, target_kingdom_id, prayer_type, ticks_remaining, ticks_total, started_at FROM kingdom_prayers
`

func (q *Queries) GetAllKingdomPrayers(ctx context.Context) ([]KingdomPrayer, error) {
	rows, err := q.db.Query(ctx, getAllKingdomPrayers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []KingdomPrayer
	for rows.Next() {
		var i KingdomPrayer
		if err := rows.Scan(
			&i.ID,
			&i.KingdomID,
			&i.TargetKingdomID,
			&i.PrayerType,
			&i.TicksRemaining,
			&i.TicksTotal,
			&i.StartedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listKingdomPrayers = `-- name: ListKingdomPrayers :many
SELECT id, kingdom_id, target_kingdom_id, prayer_type, ticks_remaining, ticks_total, started_at FROM kingdom_prayers
WHERE kingdom_id = $1
ORDER BY started_at ASC
`

func (q *Queries) ListKingdomPrayers(ctx context.Context, kingdomID int) ([]KingdomPrayer, error) {
	rows, err := q.db.Query(ctx, listKingdomPrayers, kingdomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []KingdomPrayer
	for rows.Next() {
		var i KingdomPrayer
		if err := rows.Scan(
			&i.ID,
			&i.KingdomID,
			&i.TargetKingdomID,
			&i.PrayerType,
			&i.TicksRemaining,
			&i.TicksTotal,
			&i.StartedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPrayersTargetingKingdom = `-- name: ListPrayersTargetingKingdom :many
SELECT id, kingdom_id, target_kingdom_id, prayer_type, ticks_remaining, ticks_total, started_at FROM kingdom_prayers
WHERE target_kingdom_id = $1
ORDER BY started_at ASC
`

func (q *Queries) ListPrayersTargetingKingdom(ctx context.Context, targetKingdomID int) ([]KingdomPrayer, error) {
	rows, err := q.db.Query(ctx, listPrayersTargetingKingdom, targetKingdomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []KingdomPrayer
	for rows.Next() {
		var i KingdomPrayer
		if err := rows.Scan(
			&i.ID,
			&i.KingdomID,
			&i.TargetKingdomID,
			&i.PrayerType,
			&i.TicksRemaining,
			&i.TicksTotal,
			&i.StartedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
