// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	// Atomically promotes the invited row to member if the guild is not full (< 20),
	// cancels any pending join requests for the kingdom in other guilds, and
	// cancels any other outstanding invitations. Returns no rows if the invitation
	// is not found or the guild is at capacity.
	AcceptGuildInvitation(ctx context.Context, arg AcceptGuildInvitationParams) (int, error)
	ActivateGuild(ctx context.Context, guildID int) error
	AdvanceCampaignStatus(ctx context.Context, arg AdvanceCampaignStatusParams) error
	// Atomically checks the active member count and approves the pending request
	// in one statement. Returns no rows if the guild is full (>= 20 active members)
	// or the request no longer exists, which the caller maps to the appropriate error.
	ApproveMembershipIfNotFull(ctx context.Context, arg ApproveMembershipIfNotFullParams) (int, error)
	BulkActivateCampaigns(ctx context.Context, ids []int) error
	BulkCreateMessages(ctx context.Context, arg BulkCreateMessagesParams) error
	BulkDeductKingdomUnitsCasualties(ctx context.Context, arg BulkDeductKingdomUnitsCasualtiesParams) error
	BulkDeleteCampaigns(ctx context.Context, ids []int) error
	BulkGainKingdomPopulation(ctx context.Context, arg BulkGainKingdomPopulationParams) error
	BulkInsertCombatLogParticipants(ctx context.Context, arg BulkInsertCombatLogParticipantsParams) error
	BulkReturnCampaigns(ctx context.Context, ids []int) error
	BulkTickKingdoms(ctx context.Context, arg BulkTickKingdomsParams) error
	BulkUpdateCampaignCounts(ctx context.Context, arg BulkUpdateCampaignCountsParams) error
	// Atomically verifies ownership and non-returning status, then sets the campaign
	// to returning. Returns no rows if the campaign does not exist, belongs to a
	// different kingdom, or is already returning — all treated as a no-op by the caller.
	CancelCampaign(ctx context.Context, arg CancelCampaignParams) (int, error)
	CancelJoinRequest(ctx context.Context, arg CancelJoinRequestParams) error
	CancelOtherPendingRequests(ctx context.Context, arg CancelOtherPendingRequestsParams) error
	CancelProposal(ctx context.Context, id int) error
	ConsumeEmailVerification(ctx context.Context, token string) (int, error)
	ConsumePasswordResetToken(ctx context.Context, token string) (int, error)
	CountGuildSupporters(ctx context.Context, guildID int) (int, error)
	CountUnreadMessages(ctx context.Context, toKingdomID int) (int, error)
	// Atomically checks that enough units are available (via kingdom_available_units
	// view) and inserts the campaign in one statement. Returns no rows if the
	// available count is insufficient, which the caller maps to "not enough units".
	CreateCampaignIfAvailable(ctx context.Context, arg CreateCampaignIfAvailableParams) (KingdomCampaign, error)
	CreateEmailVerification(ctx context.Context, arg CreateEmailVerificationParams) error
	CreateGuild(ctx context.Context, arg CreateGuildParams) (CreateGuildRow, error)
	CreateGuildInvitation(ctx context.Context, arg CreateGuildInvitationParams) error
	CreateGuildMembership(ctx context.Context, arg CreateGuildMembershipParams) error
	CreateKingdom(ctx context.Context, arg CreateKingdomParams) (Kingdom, error)
	CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) error
	CreatePrayer(ctx context.Context, arg CreatePrayerParams) (KingdomPrayer, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (int, error)
	DeclineGuildInvitation(ctx context.Context, arg DeclineGuildInvitationParams) (int, error)
	DecrementAndListCampaignsAtZero(ctx context.Context) ([]DecrementAndListCampaignsAtZeroRow, error)
	DecrementAndListConstructionAtZero(ctx context.Context) ([]DecrementAndListConstructionAtZeroRow, error)
	DecrementAndListPrayersAtZero(ctx context.Context) ([]DecrementAndListPrayersAtZeroRow, error)
	DecrementAndListTrainingAtZero(ctx context.Context) ([]DecrementAndListTrainingAtZeroRow, error)
	DeductBuildingCost(ctx context.Context, arg DeductBuildingCostParams) (int, error)
	DeductKingdomUnitsCasualties(ctx context.Context, arg DeductKingdomUnitsCasualtiesParams) error
	DeductUnitCost(ctx context.Context, arg DeductUnitCostParams) (int, error)
	DeleteCampaign(ctx context.Context, id int) error
	DeleteConstruction(ctx context.Context, kingdomID int) error
	DeleteEmailVerificationByUserID(ctx context.Context, userID int) error
	DeleteKingdomPrayers(ctx context.Context, ids []int) error
	DeleteMessage(ctx context.Context, arg DeleteMessageParams) error
	DeleteMessages(ctx context.Context, arg DeleteMessagesParams) error
	DeletePasswordResetTokensByUserID(ctx context.Context, userID int) error
	DeletePrayer(ctx context.Context, arg DeletePrayerParams) error
	DeleteSession(ctx context.Context, id string) error
	DeleteSessionsByUserID(ctx context.Context, userID int) error
	DeleteTraining(ctx context.Context, kingdomID int) error
	DisbandGuild(ctx context.Context, id int) error
	ExpirePendingGuilds(ctx context.Context) error
	GetActiveCampaignsReadyForCombat(ctx context.Context) ([]KingdomCampaign, error)
	GetAllKingdomBuildings(ctx context.Context) ([]KingdomBuilding, error)
	GetAllKingdomPrayers(ctx context.Context) ([]KingdomPrayer, error)
	GetAllKingdomUnits(ctx context.Context) ([]KingdomUnit, error)
	// Returns available unit counts for a kingdom via the kingdom_available_units view.
	// A unit is available if it is not committed to any campaign (any status).
	GetAvailableKingdomUnits(ctx context.Context, kingdomID int) ([]GetAvailableKingdomUnitsRow, error)
	// Bulk version of GetAvailableKingdomUnits for the combat tick.
	GetAvailableKingdomUnitsByIDs(ctx context.Context, ids []int) ([]KingdomAvailableUnit, error)
	GetCampaignsForKingdom(ctx context.Context, kingdomID int) ([]KingdomCampaign, error)
	GetGuildByID(ctx context.Context, id int) (Guild, error)
	GetGuildBySlug(ctx context.Context, slug string) (Guild, error)
	GetInboxMessageByID(ctx context.Context, arg GetInboxMessageByIDParams) (GetInboxMessageByIDRow, error)
	GetKingdomBuildings(ctx context.Context, kingdomID int) ([]KingdomBuilding, error)
	GetKingdomByID(ctx context.Context, id int) (Kingdom, error)
	GetKingdomByName(ctx context.Context, name string) (Kingdom, error)
	GetKingdomByUserID(ctx context.Context, userID int) (Kingdom, error)
	GetKingdomConstruction(ctx context.Context, kingdomID int) (KingdomConstruction, error)
	GetKingdomGuildInvitation(ctx context.Context, arg GetKingdomGuildInvitationParams) (int, error)
	GetKingdomGuildMembership(ctx context.Context, kingdomID int) (GetKingdomGuildMembershipRow, error)
	GetKingdomTraining(ctx context.Context, kingdomID int) (KingdomTraining, error)
	GetKingdomUnits(ctx context.Context, kingdomID int) ([]KingdomUnit, error)
	GetKingdomsByIDs(ctx context.Context, ids []int) ([]Kingdom, error)
	GetKingdomsByNames(ctx context.Context, names []string) ([]Kingdom, error)
	GetKingdomsInViewport(ctx context.Context, arg GetKingdomsInViewportParams) ([]GetKingdomsInViewportRow, error)
	GetLatestTickID(ctx context.Context) (int, error)
	GetMembershipByID(ctx context.Context, arg GetMembershipByIDParams) (GuildMembership, error)
	GetMembershipByKingdomAndGuild(ctx context.Context, arg GetMembershipByKingdomAndGuildParams) (GuildMembership, error)
	GetRecentCombatLogs(ctx context.Context, kingdomID int) ([]GetRecentCombatLogsRow, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserBySessionID(ctx context.Context, id string) (GetUserBySessionIDRow, error)
	IncrementKingdomBuilding(ctx context.Context, arg IncrementKingdomBuildingParams) error
	InsertCombatLog(ctx context.Context, arg InsertCombatLogParams) (int, error)
	InsertTick(ctx context.Context) (int, error)
	ListActiveGuilds(ctx context.Context) ([]ListActiveGuildsRow, error)
	ListAllKingdoms(ctx context.Context) ([]Kingdom, error)
	ListGuildInvitations(ctx context.Context, guildID int) ([]ListGuildInvitationsRow, error)
	ListGuildMembersExcludingSelf(ctx context.Context, arg ListGuildMembersExcludingSelfParams) ([]int, error)
	ListGuildMembersWithNames(ctx context.Context, guildID int) ([]ListGuildMembersWithNamesRow, error)
	ListGuildOfficersExcludingSelf(ctx context.Context, arg ListGuildOfficersExcludingSelfParams) ([]int, error)
	ListInboxMessages(ctx context.Context, toKingdomID int) ([]ListInboxMessagesRow, error)
	ListKingdomInvitations(ctx context.Context, kingdomID int) ([]ListKingdomInvitationsRow, error)
	ListKingdomPrayers(ctx context.Context, kingdomID int) ([]KingdomPrayer, error)
	ListOtherKingdoms(ctx context.Context, id int) ([]ListOtherKingdomsRow, error)
	ListPendingGuilds(ctx context.Context) ([]ListPendingGuildsRow, error)
	ListPendingRequests(ctx context.Context, guildID int) ([]ListPendingRequestsRow, error)
	ListPrayersTargetingKingdom(ctx context.Context, targetKingdomID int) ([]KingdomPrayer, error)
	MarkMessageRead(ctx context.Context, arg MarkMessageReadParams) error
	RejectMembership(ctx context.Context, arg RejectMembershipParams) error
	RemoveMembership(ctx context.Context, arg RemoveMembershipParams) error
	// Atomically checks the active member count and inserts a pending_approval row
	// in one statement. Returns no rows if the guild is full (>= 20 active members),
	// which the caller maps to "this guild is full".
	RequestJoinIfNotFull(ctx context.Context, arg RequestJoinIfNotFullParams) (GuildMembership, error)
	RevokeGuildInvitation(ctx context.Context, arg RevokeGuildInvitationParams) (int, error)
	SetMembershipRole(ctx context.Context, arg SetMembershipRoleParams) error
	StartConstruction(ctx context.Context, arg StartConstructionParams) error
	StartTraining(ctx context.Context, arg StartTrainingParams) error
	StealKingdomPopulation(ctx context.Context, arg StealKingdomPopulationParams) error
	TransferLeadership(ctx context.Context, arg TransferLeadershipParams) error
	UpdateGuildDescription(ctx context.Context, arg UpdateGuildDescriptionParams) error
	UpdateGuildSettings(ctx context.Context, arg UpdateGuildSettingsParams) error
	UpdateKingdomAllocations(ctx context.Context, arg UpdateKingdomAllocationsParams) (Kingdom, error)
	UpdateLastLogin(ctx context.Context, id int) error
	UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error
	UpsertKingdomUnits(ctx context.Context, arg UpsertKingdomUnitsParams) error
	VerifyUser(ctx context.Context, id int) error
	WithdrawSupport(ctx context.Context, arg WithdrawSupportParams) error
}

var _ Querier = (*Queries)(nil)
