// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ticks.sql

package db

import (
	"context"
)

const getLatestTickID = `-- name: GetLatestTickID :one
SELECT id FROM game_ticks ORDER BY id DESC LIMIT 1
`

func (q *Queries) GetLatestTickID(ctx context.Context) (int, error) {
	row := q.db.QueryRow(ctx, getLatestTickID)
	var id int
	err := row.Scan(&id)
	return id, err
}

const insertTick = `-- name: InsertTick :one
INSERT INTO game_ticks (occurred_at) VALUES (NOW()) RETURNING id
`

func (q *Queries) InsertTick(ctx context.Context) (int, error) {
	row := q.db.QueryRow(ctx, insertTick)
	var id int
	err := row.Scan(&id)
	return id, err
}
