// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: units.sql

package db

import (
	"context"
	"time"
)

const decrementAndListCompletedTraining = `-- name: DecrementAndListCompletedTraining :many
WITH decremented AS (
    UPDATE kingdom_training
    SET ticks_remaining = ticks_remaining - 1
    WHERE ticks_remaining > 0
    RETURNING id, kingdom_id, unit_type, count, ticks_remaining, ticks_total, started_at
)
SELECT id, kingdom_id, unit_type, count, ticks_remaining, ticks_total, started_at FROM decremented WHERE ticks_remaining = 0
`

type DecrementAndListCompletedTrainingRow struct {
	ID             int
	KingdomID      int
	UnitType       string
	Count          int
	TicksRemaining int
	TicksTotal     int
	StartedAt      time.Time
}

func (q *Queries) DecrementAndListCompletedTraining(ctx context.Context) ([]DecrementAndListCompletedTrainingRow, error) {
	rows, err := q.db.Query(ctx, decrementAndListCompletedTraining)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DecrementAndListCompletedTrainingRow
	for rows.Next() {
		var i DecrementAndListCompletedTrainingRow
		if err := rows.Scan(
			&i.ID,
			&i.KingdomID,
			&i.UnitType,
			&i.Count,
			&i.TicksRemaining,
			&i.TicksTotal,
			&i.StartedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deductUnitCost = `-- name: DeductUnitCost :one
UPDATE kingdoms SET
    wood       = wood  - $1,
    stone      = stone - $2,
    mana       = mana  - $3,
    updated_at = NOW()
WHERE id = $4
    AND wood  >= $1
    AND stone >= $2
    AND mana  >= $3
RETURNING id
`

type DeductUnitCostParams struct {
	WoodCost  int
	StoneCost int
	ManaCost  int
	KingdomID int
}

func (q *Queries) DeductUnitCost(ctx context.Context, arg DeductUnitCostParams) (int, error) {
	row := q.db.QueryRow(ctx, deductUnitCost,
		arg.WoodCost,
		arg.StoneCost,
		arg.ManaCost,
		arg.KingdomID,
	)
	var id int
	err := row.Scan(&id)
	return id, err
}

const deleteTraining = `-- name: DeleteTraining :exec
DELETE FROM kingdom_training
WHERE kingdom_id = $1
`

func (q *Queries) DeleteTraining(ctx context.Context, kingdomID int) error {
	_, err := q.db.Exec(ctx, deleteTraining, kingdomID)
	return err
}

const getAllKingdomUnits = `-- name: GetAllKingdomUnits :many
SELECT kingdom_id, unit_type, count, created_at, updated_at FROM kingdom_units
ORDER BY kingdom_id
`

func (q *Queries) GetAllKingdomUnits(ctx context.Context) ([]KingdomUnit, error) {
	rows, err := q.db.Query(ctx, getAllKingdomUnits)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []KingdomUnit
	for rows.Next() {
		var i KingdomUnit
		if err := rows.Scan(
			&i.KingdomID,
			&i.UnitType,
			&i.Count,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getKingdomTraining = `-- name: GetKingdomTraining :one
SELECT id, kingdom_id, unit_type, count, ticks_remaining, ticks_total, started_at FROM kingdom_training
WHERE kingdom_id = $1
`

func (q *Queries) GetKingdomTraining(ctx context.Context, kingdomID int) (KingdomTraining, error) {
	row := q.db.QueryRow(ctx, getKingdomTraining, kingdomID)
	var i KingdomTraining
	err := row.Scan(
		&i.ID,
		&i.KingdomID,
		&i.UnitType,
		&i.Count,
		&i.TicksRemaining,
		&i.TicksTotal,
		&i.StartedAt,
	)
	return i, err
}

const getKingdomUnits = `-- name: GetKingdomUnits :many
SELECT kingdom_id, unit_type, count, created_at, updated_at FROM kingdom_units
WHERE kingdom_id = $1
`

func (q *Queries) GetKingdomUnits(ctx context.Context, kingdomID int) ([]KingdomUnit, error) {
	rows, err := q.db.Query(ctx, getKingdomUnits, kingdomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []KingdomUnit
	for rows.Next() {
		var i KingdomUnit
		if err := rows.Scan(
			&i.KingdomID,
			&i.UnitType,
			&i.Count,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const startTraining = `-- name: StartTraining :exec
INSERT INTO kingdom_training (kingdom_id, unit_type, count, ticks_remaining, ticks_total)
VALUES ($1, $2, $3, $4, $4)
`

type StartTrainingParams struct {
	KingdomID      int
	UnitType       string
	Count          int
	TicksRemaining int
}

func (q *Queries) StartTraining(ctx context.Context, arg StartTrainingParams) error {
	_, err := q.db.Exec(ctx, startTraining,
		arg.KingdomID,
		arg.UnitType,
		arg.Count,
		arg.TicksRemaining,
	)
	return err
}

const upsertKingdomUnits = `-- name: UpsertKingdomUnits :exec
INSERT INTO kingdom_units (kingdom_id, unit_type, count)
VALUES ($1, $2, $3)
ON CONFLICT (kingdom_id, unit_type)
DO UPDATE SET
    count      = kingdom_units.count + $3,
    updated_at = NOW()
`

type UpsertKingdomUnitsParams struct {
	KingdomID int
	UnitType  string
	Count     int
}

func (q *Queries) UpsertKingdomUnits(ctx context.Context, arg UpsertKingdomUnitsParams) error {
	_, err := q.db.Exec(ctx, upsertKingdomUnits, arg.KingdomID, arg.UnitType, arg.Count)
	return err
}
