// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: units.sql

package db

import (
	"context"
	"time"
)

const bulkDeductKingdomUnitsCasualties = `-- name: BulkDeductKingdomUnitsCasualties :exec
UPDATE kingdom_units
SET count = GREATEST(0, count - data.casualties), updated_at = NOW()
FROM (
    SELECT
        unnest($1::bigint[]) AS kingdom_id,
        unnest($2::text[])    AS unit_type,
        unnest($3::int[])     AS casualties
) AS data
WHERE kingdom_units.kingdom_id = data.kingdom_id
  AND kingdom_units.unit_type  = data.unit_type
`

type BulkDeductKingdomUnitsCasualtiesParams struct {
	KingdomIds []int
	UnitTypes  []string
	Casualties []int
}

func (q *Queries) BulkDeductKingdomUnitsCasualties(ctx context.Context, arg BulkDeductKingdomUnitsCasualtiesParams) error {
	_, err := q.db.Exec(ctx, bulkDeductKingdomUnitsCasualties, arg.KingdomIds, arg.UnitTypes, arg.Casualties)
	return err
}

const cancelTrainingWithRefund = `-- name: CancelTrainingWithRefund :exec
WITH deleted AS (
    DELETE FROM kingdom_training WHERE kingdom_id = $4 AND kingdom_training.id = $5 RETURNING id, kingdom_id, unit_type, count, ticks_remaining, ticks_total, started_at
)
UPDATE kingdoms SET
    wood  = wood  + $1,
    stone = stone + $2,
    mana  = mana  + $3,
    updated_at = NOW()
FROM deleted
WHERE kingdoms.id = $4
`

type CancelTrainingWithRefundParams struct {
	WoodRefund  int
	StoneRefund int
	ManaRefund  int
	KingdomID   int
	TrainingID  int
}

// Atomically deletes the training row and refunds the resource cost back to the
// kingdom. The UPDATE runs only when a row was actually deleted (via the FROM
// deleted join), so if the tick already completed training before this fires
// the kingdom is not credited twice.
func (q *Queries) CancelTrainingWithRefund(ctx context.Context, arg CancelTrainingWithRefundParams) error {
	_, err := q.db.Exec(ctx, cancelTrainingWithRefund,
		arg.WoodRefund,
		arg.StoneRefund,
		arg.ManaRefund,
		arg.KingdomID,
		arg.TrainingID,
	)
	return err
}

const decrementAndListTrainingAtZero = `-- name: DecrementAndListTrainingAtZero :many
WITH decremented AS (
    UPDATE kingdom_training
    SET ticks_remaining = ticks_remaining - 1
    WHERE ticks_remaining > 0
    RETURNING id, kingdom_id, unit_type, count, ticks_remaining, ticks_total, started_at
)
SELECT id, kingdom_id, unit_type, count, ticks_remaining, ticks_total, started_at FROM decremented WHERE ticks_remaining = 0
`

type DecrementAndListTrainingAtZeroRow struct {
	ID             int
	KingdomID      int
	UnitType       string
	Count          int
	TicksRemaining int
	TicksTotal     int
	StartedAt      time.Time
}

func (q *Queries) DecrementAndListTrainingAtZero(ctx context.Context) ([]DecrementAndListTrainingAtZeroRow, error) {
	rows, err := q.db.Query(ctx, decrementAndListTrainingAtZero)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DecrementAndListTrainingAtZeroRow
	for rows.Next() {
		var i DecrementAndListTrainingAtZeroRow
		if err := rows.Scan(
			&i.ID,
			&i.KingdomID,
			&i.UnitType,
			&i.Count,
			&i.TicksRemaining,
			&i.TicksTotal,
			&i.StartedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deductKingdomUnitsCasualties = `-- name: DeductKingdomUnitsCasualties :exec
UPDATE kingdom_units
SET count = GREATEST(0, count - $1), updated_at = NOW()
WHERE kingdom_id = $2
  AND unit_type = $3
`

type DeductKingdomUnitsCasualtiesParams struct {
	Casualties int
	KingdomID  int
	UnitType   string
}

func (q *Queries) DeductKingdomUnitsCasualties(ctx context.Context, arg DeductKingdomUnitsCasualtiesParams) error {
	_, err := q.db.Exec(ctx, deductKingdomUnitsCasualties, arg.Casualties, arg.KingdomID, arg.UnitType)
	return err
}

const deductUnitCost = `-- name: DeductUnitCost :one
UPDATE kingdoms SET
    wood       = wood  - $1,
    stone      = stone - $2,
    mana       = mana  - $3,
    updated_at = NOW()
WHERE id = $4
    AND wood  >= $1
    AND stone >= $2
    AND mana  >= $3
RETURNING id
`

type DeductUnitCostParams struct {
	WoodCost  int
	StoneCost int
	ManaCost  int
	KingdomID int
}

func (q *Queries) DeductUnitCost(ctx context.Context, arg DeductUnitCostParams) (int, error) {
	row := q.db.QueryRow(ctx, deductUnitCost,
		arg.WoodCost,
		arg.StoneCost,
		arg.ManaCost,
		arg.KingdomID,
	)
	var id int
	err := row.Scan(&id)
	return id, err
}

const deleteTraining = `-- name: DeleteTraining :exec
DELETE FROM kingdom_training
WHERE kingdom_id = $1
`

func (q *Queries) DeleteTraining(ctx context.Context, kingdomID int) error {
	_, err := q.db.Exec(ctx, deleteTraining, kingdomID)
	return err
}

const getAllKingdomUnits = `-- name: GetAllKingdomUnits :many
SELECT kingdom_id, unit_type, count, created_at, updated_at FROM kingdom_units
ORDER BY kingdom_id
`

func (q *Queries) GetAllKingdomUnits(ctx context.Context) ([]KingdomUnit, error) {
	rows, err := q.db.Query(ctx, getAllKingdomUnits)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []KingdomUnit
	for rows.Next() {
		var i KingdomUnit
		if err := rows.Scan(
			&i.KingdomID,
			&i.UnitType,
			&i.Count,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAvailableKingdomUnits = `-- name: GetAvailableKingdomUnits :many
SELECT unit_type, count FROM kingdom_available_units
WHERE kingdom_id = $1
`

type GetAvailableKingdomUnitsRow struct {
	UnitType string
	Count    int
}

// Returns available unit counts for a kingdom via the kingdom_available_units view.
// A unit is available if it is not committed to any campaign (any status).
func (q *Queries) GetAvailableKingdomUnits(ctx context.Context, kingdomID int) ([]GetAvailableKingdomUnitsRow, error) {
	rows, err := q.db.Query(ctx, getAvailableKingdomUnits, kingdomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAvailableKingdomUnitsRow
	for rows.Next() {
		var i GetAvailableKingdomUnitsRow
		if err := rows.Scan(&i.UnitType, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAvailableKingdomUnitsByIDs = `-- name: GetAvailableKingdomUnitsByIDs :many
SELECT kingdom_id, unit_type, count FROM kingdom_available_units
WHERE kingdom_id = ANY($1::bigint[])
`

// Bulk version of GetAvailableKingdomUnits for the combat tick.
func (q *Queries) GetAvailableKingdomUnitsByIDs(ctx context.Context, ids []int) ([]KingdomAvailableUnit, error) {
	rows, err := q.db.Query(ctx, getAvailableKingdomUnitsByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []KingdomAvailableUnit
	for rows.Next() {
		var i KingdomAvailableUnit
		if err := rows.Scan(&i.KingdomID, &i.UnitType, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getKingdomTraining = `-- name: GetKingdomTraining :one
SELECT id, kingdom_id, unit_type, count, ticks_remaining, ticks_total, started_at FROM kingdom_training
WHERE kingdom_id = $1
`

func (q *Queries) GetKingdomTraining(ctx context.Context, kingdomID int) (KingdomTraining, error) {
	row := q.db.QueryRow(ctx, getKingdomTraining, kingdomID)
	var i KingdomTraining
	err := row.Scan(
		&i.ID,
		&i.KingdomID,
		&i.UnitType,
		&i.Count,
		&i.TicksRemaining,
		&i.TicksTotal,
		&i.StartedAt,
	)
	return i, err
}

const getKingdomUnits = `-- name: GetKingdomUnits :many
SELECT kingdom_id, unit_type, count, created_at, updated_at FROM kingdom_units
WHERE kingdom_id = $1
`

func (q *Queries) GetKingdomUnits(ctx context.Context, kingdomID int) ([]KingdomUnit, error) {
	rows, err := q.db.Query(ctx, getKingdomUnits, kingdomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []KingdomUnit
	for rows.Next() {
		var i KingdomUnit
		if err := rows.Scan(
			&i.KingdomID,
			&i.UnitType,
			&i.Count,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const startTraining = `-- name: StartTraining :exec
INSERT INTO kingdom_training (kingdom_id, unit_type, count, ticks_remaining, ticks_total)
VALUES ($1, $2, $3, $4, $4)
`

type StartTrainingParams struct {
	KingdomID      int
	UnitType       string
	Count          int
	TicksRemaining int
}

func (q *Queries) StartTraining(ctx context.Context, arg StartTrainingParams) error {
	_, err := q.db.Exec(ctx, startTraining,
		arg.KingdomID,
		arg.UnitType,
		arg.Count,
		arg.TicksRemaining,
	)
	return err
}

const upsertKingdomUnits = `-- name: UpsertKingdomUnits :exec
INSERT INTO kingdom_units (kingdom_id, unit_type, count)
VALUES ($1, $2, $3)
ON CONFLICT (kingdom_id, unit_type)
DO UPDATE SET
    count      = kingdom_units.count + $3,
    updated_at = NOW()
`

type UpsertKingdomUnitsParams struct {
	KingdomID int
	UnitType  string
	Count     int
}

func (q *Queries) UpsertKingdomUnits(ctx context.Context, arg UpsertKingdomUnitsParams) error {
	_, err := q.db.Exec(ctx, upsertKingdomUnits, arg.KingdomID, arg.UnitType, arg.Count)
	return err
}
