// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Resource struct {
	ID    int64
	Wood  int32
	Stone int32
	Food  int32
}

type User struct {
	ID        int64
	Email     string
	IsActive  bool
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}
