// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: resources.sql

package database

import (
	"context"
)

const createResource = `-- name: CreateResource :one
INSERT INTO resources (wood, stone, food)
VALUES ($1, $2, $3)
RETURNING id, wood, stone, food
`

type CreateResourceParams struct {
	Wood  int32
	Stone int32
	Food  int32
}

func (q *Queries) CreateResource(ctx context.Context, arg CreateResourceParams) (Resource, error) {
	row := q.db.QueryRow(ctx, createResource, arg.Wood, arg.Stone, arg.Food)
	var i Resource
	err := row.Scan(
		&i.ID,
		&i.Wood,
		&i.Stone,
		&i.Food,
	)
	return i, err
}

const listResources = `-- name: ListResources :many
SELECT id,
  wood,
  stone,
  food
FROM resources
ORDER BY id ASC
`

func (q *Queries) ListResources(ctx context.Context) ([]Resource, error) {
	rows, err := q.db.Query(ctx, listResources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Resource
	for rows.Next() {
		var i Resource
		if err := rows.Scan(
			&i.ID,
			&i.Wood,
			&i.Stone,
			&i.Food,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
