package routes

// Route paths for all feature packages.
// Centralised here to break the import cycle between internal/ui and handler packages.
const (
	HomePath = "/home"
	ChatPath = "/chat"

	KingdomPath                  = "/kingdom"
	KingdomSetupPath             = "/kingdom/setup"
	KingdomCreatePath            = "/kingdom/create"
	KingdomAllocationPath        = "/kingdom/allocation"
	KingdomAllocationSavePath    = "/kingdom/allocation/save"
	KingdomRefreshPath           = "/kingdom/refresh"
	KingdomAllocationRefreshPath = "/kingdom/allocation/refresh"

	KingdomBuildingsPath        = "/kingdom/buildings"
	KingdomBuildingsRefreshPath = "/kingdom/buildings/refresh"
	KingdomBuildingsDetailPath  = "/kingdom/buildings/detail"
	KingdomBuildingsRaisePath   = "/kingdom/buildings/raise"

	KingdomUnitsPath        = "/kingdom/units"
	KingdomUnitsRefreshPath = "/kingdom/units/refresh"
	KingdomUnitsTrainPath   = "/kingdom/units/train"
	KingdomUnitsCancelPath  = "/kingdom/units/cancel"

	KingdomMapPath     = "/kingdom/map"
	KingdomMapFindPath = "/kingdom/map/find"

	KingdomArmyPath         = "/kingdom/army"
	KingdomArmyRefreshPath  = "/kingdom/army/refresh"
	KingdomArmySendPath     = "/kingdom/army/send"
	KingdomArmyCancelPath   = "/kingdom/army/cancel/{id}"
	KingdomArmyTransferPath = "/kingdom/army/transfer"
	KingdomArmyDisbandPath  = "/kingdom/army/disband/{id}"

	KingdomLayoutRefreshPath = "/kingdom/layout/refresh"

	KingdomMessagesPath                 = "/kingdom/messages"
	KingdomMessagesRefreshPath          = "/kingdom/messages/refresh"
	KingdomMessagesViewPath             = "/kingdom/messages/view"
	KingdomMessagesComposePath          = "/kingdom/messages/compose"
	KingdomMessagesSendPath             = "/kingdom/messages/send"
	KingdomMessagesDeletePath           = "/kingdom/messages/delete/{id}"
	KingdomMessagesDeleteManyPath       = "/kingdom/messages/delete-many"
	KingdomMessagesGuildComposePath     = "/kingdom/messages/guild-message/compose"
	KingdomMessagesGuildMessageSendPath = "/kingdom/messages/guild-message/send"

	KingdomPrayersPath        = "/kingdom/prayers"
	KingdomPrayersRefreshPath = "/kingdom/prayers/refresh"
	KingdomPrayerCastPath     = "/kingdom/prayers/cast"
	KingdomPrayerCancelPath   = "/kingdom/prayers/cancel/{id}"

	GuildPath                   = "/guild"
	GuildRefreshPath            = "/guild/refresh"
	GuildListPath               = "/guild/list"
	GuildNewPath                = "/guild/new"
	GuildCreatePath             = "/guild/create"
	GuildViewPath               = "/guild/{slug}" // guild names are 5 character minimum; prevents shadowing /guild/{5} routes  like new and list
	GuildViewRefreshPath        = "/guild/{slug}/refresh"
	GuildManagePath             = "/guild/{slug}/manage"
	GuildManageRefreshPath      = "/guild/{slug}/manage/refresh"
	GuildSupportPath            = "/guild/{slug}/support"
	GuildWithdrawSupportPath    = "/guild/{slug}/withdraw-support"
	GuildCancelProposalPath     = "/guild/{slug}/cancel-proposal"
	GuildRequestJoinPath        = "/guild/{slug}/request"
	GuildCancelRequestPath      = "/guild/{slug}/cancel-request"
	GuildApproveMemberPath      = "/guild/{slug}/members/{id}/approve"
	GuildRejectMemberPath       = "/guild/{slug}/members/{id}/reject"
	GuildRemoveMemberPath       = "/guild/{slug}/members/{id}/remove"
	GuildPromotePath            = "/guild/{slug}/members/{id}/promote"
	GuildDemotePath             = "/guild/{slug}/members/{id}/demote"
	GuildTransferLeadershipPath = "/guild/{slug}/transfer-leadership"
	GuildLeavePath              = "/guild/{slug}/leave"
	GuildDisbandPath            = "/guild/{slug}/disband"
	GuildEditDescriptionPath    = "/guild/{slug}/edit-description"
	GuildSettingsPath           = "/guild/{slug}/settings"
	GuildSettingsSavePath       = "/guild/{slug}/settings/save"
	GuildInvitePath             = "/guild/{slug}/invite"
	GuildInvitationAcceptPath   = "/guild/{slug}/invitations/{id}/accept"
	GuildInvitationDeclinePath  = "/guild/{slug}/invitations/{id}/decline"
	GuildInvitationRevokePath   = "/guild/{slug}/invitations/{id}/revoke"

	LoginPath              = "/login"
	RegisterPath           = "/register"
	VerifyPath             = "/verify"
	LogoutPath             = "/logout"
	ForgotPasswordPath     = "/forgot-password"
	ResetPasswordPath      = "/reset-password"
	ResendVerificationPath = "/resend-verification"
)
